AddCSLuaFile("cl_init.lua")
AddCSLuaFile("shared.lua")
AddCSLuaFile("lod/sh_config.lua")
AddCSLuaFile("lod/sh_rng.lua")
AddCSLuaFile("lod/cl_textured_box.lua")
AddCSLuaFile("lod/cl_debug.lua")
AddCSLuaFile("lod/cl_hud.lua")
AddCSLuaFile("lod/cl_dev_testing.lua")
AddCSLuaFile("lod/cl_hit_confirm.lua")
AddCSLuaFile("lod/cl_minimap.lua")
AddCSLuaFile("lod/cl_minimap_origin_sync.lua")
AddCSLuaFile("lod/cl_minimap_safety.lua")

include("shared.lua")
include("lod/sv_maze_generator.lua")
include("lod/sv_graph_integrity.lua")
include("lod/sv_maze_builder.lua")
include("lod/sv_maze_builder_static_walls.lua")
include("lod/sv_maze_builder_floor_anchor.lua")
-- Back the raised level-0 labyrinth with one continuous recessed steel underdeck
-- so container-base/corner sightlines can never reveal the host map surface.
include("lod/sv_ground_perimeter_seals.lua")
include("lod/sv_m1_stair_geometry.lua")
include("lod/sv_maze_navigator.lua")
include("lod/sv_faction_manager.lua")
include("lod/sv_m3_enemy_config.lua")
include("lod/sv_progression_director.lua")
include("lod/sv_m2_progression_safety.lua")
include("lod/sv_progression_builder.lua")
include("lod/sv_maze_geometry_audit.lua")
include("lod/sv_vertical_transition_audit.lua")
include("lod/sv_encounter_director.lua")
include("lod/sv_m3_dense_testing.lua")
include("lod/sv_m3_run_integration.lua")
include("lod/sv_run_manager.lua")
include("lod/sv_minimap.lua")
include("lod/sv_minimap_canonical.lua")
include("lod/sv_minimap_safety.lua")
include("lod/sv_combat_audio.lua")

-- Motion V2 is the one production ground-movement authority. Load it before
-- archetype/variance wrappers so their existing state machines wrap the new
-- graph-authoritative kinematic kernel rather than CLuaLocomotion:Approach.
include("lod/sv_hostile_motion_v2.lua")
include("lod/sv_deadcrab.lua")
include("lod/sv_bioblaster.lua")
include("lod/sv_enemy_variance.lua")
include("lod/sv_wandering_director.lua")
include("lod/sv_encounter_spawn_variance.lua")
include("lod/sv_hostile_separation.lua")

-- The former planar/ground-bridge/stair/no-progress recovery modules remain in
-- the repository for rollback/history but are intentionally NOT loaded. They all
-- attempted to repair Source NextBot ground locomotion after the fact and must
-- not compete with Motion V2.
include("lod/sv_m3_ground_probe.lua")
include("lod/sv_hostile_combat_hulls.lua")
include("lod/sv_m3_hit_feedback.lua")
-- Load after hit feedback so generated-cover rejection can also suppress false
-- hit-confirm/flinch events, independent of EntityTakeDamage hook order.
include("lod/sv_generated_geometry_ballistics.lua")
include("lod/sv_hostile_death_audio.lua")
include("lod/sv_hostile_death_pose.lua")
include("lod/sv_hostile_hurt_pose.lua")
include("lod/sv_m3_damage_audit.lua")
include("lod/sv_campaign_restart.lua")
include("lod/sv_respawn_hud.lua")
include("lod/sv_debug_tools.lua")
include("lod/sv_m1_floor_support.lua")
include("lod/sv_m1_traversal.lua")
include("lod/sv_m2_debug.lua")
include("lod/sv_m2_seed_test_incremental.lua")
include("lod/sv_m3_debug.lua")
include("lod/sv_m3_testkit_qol.lua")
include("lod/sv_m3_roster_debug.lua")
