AddCSLuaFile("cl_init.lua")
AddCSLuaFile("shared.lua")
AddCSLuaFile("lod/sh_config.lua")
AddCSLuaFile("lod/sh_rng.lua")
AddCSLuaFile("lod/sh_tetris.lua")
AddCSLuaFile("lod/cl_textured_box.lua")
AddCSLuaFile("lod/cl_wall_visuals.lua")
AddCSLuaFile("lod/cl_container_wayfinding_projection.lua")
AddCSLuaFile("lod/cl_container_section_recolor.lua")
AddCSLuaFile("lod/cl_container_marking_panel.lua")
AddCSLuaFile("lod/cl_debug.lua")
AddCSLuaFile("lod/cl_hud.lua")
AddCSLuaFile("lod/cl_tetris.lua")
AddCSLuaFile("lod/cl_magic_hud.lua")
AddCSLuaFile("lod/cl_dev_testing.lua")
AddCSLuaFile("lod/cl_hit_confirm.lua")
AddCSLuaFile("lod/cl_combat_roll_feed.lua")
AddCSLuaFile("lod/cl_melee_contact_audit.lua")
AddCSLuaFile("lod/cl_hostile_damage_audit.lua")
AddCSLuaFile("lod/cl_minimap.lua")
AddCSLuaFile("lod/cl_minimap_reliability.lua")
AddCSLuaFile("lod/cl_minimap_logical_cell.lua")
AddCSLuaFile("lod/cl_topology_sync_safety.lua")
AddCSLuaFile("lod/cl_soldier_shot_contract.lua")
AddCSLuaFile("lod/cl_player_weapon_specials.lua")
AddCSLuaFile("lod/cl_magnum_aim_state.lua")
AddCSLuaFile("lod/cl_watcher.lua")
AddCSLuaFile("lod/cl_watcher_polish.lua")
AddCSLuaFile("lod/cl_hostile_presentation_safety.lua")
AddCSLuaFile("lod/cl_seeker.lua")
AddCSLuaFile("lod/cl_magic.lua")
AddCSLuaFile("lod/cl_pushback_fx.lua")

include("shared.lua")
include("lod/sh_tetris.lua")
include("lod/sv_saverestore_safety.lua")
include("lod/sv_midnight_sky.lua")
include("lod/sv_maze_generator.lua")
include("lod/sv_graph_integrity.lua")
include("lod/sv_wall_visuals.lua")
include("lod/sv_maze_builder.lua")
include("lod/sv_maze_builder_static_walls.lua")
include("lod/sv_maze_builder_floor_anchor.lua")
include("lod/sv_ground_perimeter_seals.lua")
include("lod/sv_m1_stair_geometry.lua")
include("lod/sv_maze_navigator.lua")
include("lod/sv_faction_manager.lua")
include("lod/sv_m3_enemy_config.lua")
include("lod/sv_combat_rolls.lua")
include("lod/sv_enemy_melee_dice_balance.lua")
-- Event-only server/client snapshot for any hostile-caused player damage. This
-- closes the old melee-audit blind spot for Seeker/Soldier/special damage and
-- performs no recurring work while combat is idle.
include("lod/sv_hostile_damage_audit.lua")
include("lod/sv_dice_ammo.lua")
include("lod/sv_player_weapon_specials.lua")
include("lod/sv_player_weapon_specials_input.lua")
include("lod/sv_progression_director.lua")
include("lod/sv_m2_progression_safety.lua")
include("lod/sv_progression_builder.lua")
include("lod/sv_maze_geometry_audit.lua")
include("lod/sv_vertical_transition_audit.lua")
include("lod/sv_encounter_director.lua")
include("lod/sv_m3_dense_testing.lua")
include("lod/sv_m3_run_integration.lua")
include("lod/sv_run_manager.lua")
include("lod/sv_loot_director.lua")
include("lod/sv_loot_context_rules.lua")
include("lod/sv_loot_catchup.lua")
include("lod/sv_loot_budget_validation.lua")
include("lod/sv_firearm_economy_equalization.lua")
include("lod/sv_minimap.lua")
include("lod/sv_topology_sync_safety.lua")
include("lod/sv_combat_audio.lua")
include("lod/sv_hostile_motion_v2.lua")
include("lod/sv_hostile_visibility_safety.lua")
include("lod/sv_deadcrab.lua")
include("lod/sv_deadcrab_latch_parent_safety.lua")
include("lod/sv_bioblaster.lua")
include("lod/sv_enemy_variance.lua")
include("lod/sv_wandering_director.lua")
include("lod/sv_encounter_spawn_variance.lua")
include("lod/sv_hostile_separation.lua")
include("lod/sv_m3_ground_probe.lua")
include("lod/sv_hostile_combat_hulls.lua")
include("lod/sv_m3_hit_feedback.lua")
include("lod/sv_shotgun_identity_balance.lua")
include("lod/sv_pushback.lua")
include("lod/sv_magic.lua")
include("lod/sv_shotgun_pushback.lua")
include("lod/sv_generated_geometry_ballistics.lua")
include("lod/sv_magnum_piercing.lua")
include("lod/sv_magnum_super_explosive.lua")
include("lod/sv_magnum_aim_state.lua")
include("lod/sv_weapon_balance_pass.lua")
include("lod/sv_magnum_ammo_drop_tuning.lua")
include("lod/sv_shotgun_ammo_tuning.lua")
include("lod/sv_shotgun_seventh_shell_fix.lua")
include("lod/sv_loot_campaign_decay.lua")
include("lod/sv_phase_zero_runtime_optimization.lua")
include("lod/sv_watcher.lua")
include("lod/sv_watcher_test_visibility.lua")
include("lod/sv_seeker.lua")
include("lod/sv_seeker_sound_safety.lua")
include("lod/sv_seeker_encounter.lua")
include("lod/sv_seeker_spawn_reliability.lua")
include("lod/sv_device_motion_safety.lua")
include("lod/sv_seeker_personality.lua")
include("lod/sv_seeker_close_range_continuity.lua")
include("lod/sv_hostile_death_audio.lua")
include("lod/sv_hostile_death_pose.lua")
include("lod/sv_hostile_hurt_pose.lua")
include("lod/sv_m3_damage_audit.lua")
include("lod/sv_campaign_restart.lua")
include("lod/sv_respawn_hud.lua")
include("lod/sv_death_tetris.lua")
include("lod/sv_soldier_shot_contract.lua")

-- Always load the unified Watcher module synchronously from this gamemode file.
-- This registers its diagnostics while relative include resolution is valid.
include("lod/sv_watcher_unified.lua")
-- Explicit per-instance transition guarantee: scan completion must always leave
-- the stationary attack state and seed the unified retreat/concealment routine.
include("lod/sv_watcher_scan_escape_handoff.lua")
-- Direct instance dispatch happens at RunBehaviour, so unrelated archetypes retain
-- their native _BehaviourTick/helper method chain.
include("lod/sv_watcher_instance_dispatch.lua")

-- Finite startup diagnostics only. Do not clear or re-install the controller here:
-- production hostiles may spawn after these callbacks, so the final class marker
-- must remain armed for the instance dispatcher throughout the run.
local function reportWatcherUnifiedReady(reason)
    local stored = scripted_ents.GetStored("lod_hostile")
    local class = stored and stored.t
    local ready = class and class.LODWatcherUnifiedControllerInstalled == true
    print("[LOD:WATCHER-UNIFIED] startup status " .. tostring(reason) .. " ready=" .. tostring(ready))
end

timer.Simple(0, function() reportWatcherUnifiedReady("next-tick") end)
hook.Add("InitPostEntity", "LOD_WatcherUnifiedLateBind", function()
    reportWatcherUnifiedReady("InitPostEntity")
end)
timer.Simple(1.0, function() reportWatcherUnifiedReady("one-second") end)

local cvDeveloperMode = GetConVar("lod_developer_mode")
LOD.DeveloperToolsLoaded = cvDeveloperMode and cvDeveloperMode:GetBool() or false
LOD.DeveloperToolModuleCount = 0
if LOD.DeveloperToolsLoaded then
    include("lod/sv_debug_tools.lua")
    include("lod/sv_m1_floor_support.lua")
    include("lod/sv_m1_traversal.lua")
    include("lod/sv_m2_debug.lua")
    include("lod/sv_m2_seed_test_incremental.lua")
    include("lod/sv_m3_debug.lua")
    include("lod/sv_m3_testkit_qol.lua")
    include("lod/sv_m3_roster_debug.lua")
    LOD.DeveloperToolModuleCount = 8
end
