LOD = LOD or {}
LOD.RPG = LOD.RPG or {}

local RPG = LOD.RPG
RPG.IdentityCatalog = RPG.IdentityCatalog or {}
local Catalog = RPG.IdentityCatalog

-- Authoritative Gate B data transcribed from the exact live GDD.
Catalog.SourceDocumentId = "1OSpgiWyiGmUCLFdq--WmCSZe6KQIr7_UTkQZklPV8lY"
Catalog.SourceRevisionId = "AIroW36vGASuk2aNYp1m4rVMnq-x3_k7IX_MCXny8aKkQnahykxbVFK5H612KfrOoS1fXUt3Pktx7zNWBYJtoDfI-c5K2iJSammBNBhzvA"

Catalog.Origins = {
    [1] = {tableType = "origin", tableIndex = 1, categoryName = "Alabama", flavorText = "You can get turned around anywhere, but apparently not on the way home."},
    [2] = {tableType = "origin", tableIndex = 2, categoryName = "Alaska", flavorText = "Distances stopped being impressive a long time ago."},
    [3] = {tableType = "origin", tableIndex = 3, categoryName = "Arizona", flavorText = "You know exactly when 'dry heat' has become somebody else's problem."},
    [4] = {tableType = "origin", tableIndex = 4, categoryName = "Arkansas", flavorText = "The scenic route is still a route."},
    [5] = {tableType = "origin", tableIndex = 5, categoryName = "California", flavorText = "If the corridor is moving, so are you."},
    [6] = {tableType = "origin", tableIndex = 6, categoryName = "Colorado", flavorText = "Up is just another direction."},
    [7] = {tableType = "origin", tableIndex = 7, categoryName = "Connecticut", flavorText = "Anything over forty minutes is an expedition."},
    [8] = {tableType = "origin", tableIndex = 8, categoryName = "Delaware", flavorText = "Not much room to waste motion."},
    [9] = {tableType = "origin", tableIndex = 9, categoryName = "Florida", flavorText = "If the sky starts making noises, you move."},
    [10] = {tableType = "origin", tableIndex = 10, categoryName = "Georgia", flavorText = "A little sweetness helps."},
    [11] = {tableType = "origin", tableIndex = 11, categoryName = "Hawaii", flavorText = "You have opinions about connections between landmasses."},
    [12] = {tableType = "origin", tableIndex = 12, categoryName = "Idaho", flavorText = "Nobody laughs at potatoes when they're dying."},
    [13] = {tableType = "origin", tableIndex = 13, categoryName = "Illinois", flavorText = "The streets taught you to think in rectangles."},
    [14] = {tableType = "origin", tableIndex = 14, categoryName = "Indiana", flavorText = "Somebody around here always knows a guy with a wrench."},
    [15] = {tableType = "origin", tableIndex = 15, categoryName = "Iowa", flavorText = "Parallel lines are calming."},
    [16] = {tableType = "origin", tableIndex = 16, categoryName = "Kansas", flavorText = "No hill is going to ambush you today."},
    [17] = {tableType = "origin", tableIndex = 17, categoryName = "Kentucky", flavorText = "When the gate drops, go."},
    [18] = {tableType = "origin", tableIndex = 18, categoryName = "Louisiana", flavorText = "You learned to keep your feet where the ground has opinions."},
    [19] = {tableType = "origin", tableIndex = 19, categoryName = "Maine", flavorText = "Find the fixed thing. Walk toward it."},
    [20] = {tableType = "origin", tableIndex = 20, categoryName = "Maryland", flavorText = "This is not how you expected regional knowledge to pay off."},
    [21] = {tableType = "origin", tableIndex = 21, categoryName = "Massachusetts", flavorText = "The direct route is a recent invention."},
    [22] = {tableType = "origin", tableIndex = 22, categoryName = "Michigan", flavorText = "Cold fingers, firm grip."},
    [23] = {tableType = "origin", tableIndex = 23, categoryName = "Minnesota", flavorText = "Calm is a competitive advantage."},
    [24] = {tableType = "origin", tableIndex = 24, categoryName = "Mississippi", flavorText = "Pick a direction and keep flowing."},
    [25] = {tableType = "origin", tableIndex = 25, categoryName = "Missouri", flavorText = "You believe evidence."},
    [26] = {tableType = "origin", tableIndex = 26, categoryName = "Montana", flavorText = "Some targets look better with room around them."},
    [27] = {tableType = "origin", tableIndex = 27, categoryName = "Nebraska", flavorText = "Rows, horizon, destination."},
    [28] = {tableType = "origin", tableIndex = 28, categoryName = "Nevada", flavorText = "The house usually wins. Today you are the house."},
    [29] = {tableType = "origin", tableIndex = 29, categoryName = "New Hampshire", flavorText = "Independence has a magazine release."},
    [30] = {tableType = "origin", tableIndex = 30, categoryName = "New Jersey", flavorText = "You've missed an exit before."},
    [31] = {tableType = "origin", tableIndex = 31, categoryName = "New Mexico", flavorText = "Distance makes details simpler."},
    [32] = {tableType = "origin", tableIndex = 32, categoryName = "New York", flavorText = "Nobody stops in the middle of the sidewalk."},
    [33] = {tableType = "origin", tableIndex = 33, categoryName = "North Carolina", flavorText = "Three points define a plane. Apparently they also define you."},
    [34] = {tableType = "origin", tableIndex = 34, categoryName = "North Dakota", flavorText = "Warm-up is optional."},
    [35] = {tableType = "origin", tableIndex = 35, categoryName = "Ohio", flavorText = "For reasons nobody can explain, you're already headed there."},
    [36] = {tableType = "origin", tableIndex = 36, categoryName = "Oklahoma", flavorText = "When the warning starts, you know where not to stand."},
    [37] = {tableType = "origin", tableIndex = 37, categoryName = "Oregon", flavorText = "A path is a path if your feet agree."},
    [38] = {tableType = "origin", tableIndex = 38, categoryName = "Pennsylvania", flavorText = "You appreciate structural milestones."},
    [39] = {tableType = "origin", tableIndex = 39, categoryName = "Rhode Island", flavorText = "Everything important should fit on one screen."},
    [40] = {tableType = "origin", tableIndex = 40, categoryName = "South Carolina", flavorText = "You bend, you don't volunteer to break."},
    [41] = {tableType = "origin", tableIndex = 41, categoryName = "South Dakota", flavorText = "Loose ground teaches honest balance."},
    [42] = {tableType = "origin", tableIndex = 42, categoryName = "Tennessee", flavorText = "You can find the beat in almost anything."},
    [43] = {tableType = "origin", tableIndex = 43, categoryName = "Texas", flavorText = "If it's way over there, it is still your business."},
    [44] = {tableType = "origin", tableIndex = 44, categoryName = "Utah", flavorText = "Zigzagging downward still counts as progress."},
    [45] = {tableType = "origin", tableIndex = 45, categoryName = "Vermont", flavorText = "Emergency syrup was not in the manual."},
    [46] = {tableType = "origin", tableIndex = 46, categoryName = "Virginia", flavorText = "You carry yourself like the map owes you an explanation."},
    [47] = {tableType = "origin", tableIndex = 47, categoryName = "Washington", flavorText = "Bad weather is not a reason to be late."},
    [48] = {tableType = "origin", tableIndex = 48, categoryName = "West Virginia", flavorText = "You distrust any route that doesn't climb somewhere."},
    [49] = {tableType = "origin", tableIndex = 49, categoryName = "Wisconsin", flavorText = "A medically dubious but emotionally sound principle."},
    [50] = {tableType = "origin", tableIndex = 50, categoryName = "Wyoming", flavorText = "Some people need personal space. You need acreage."},
    [51] = {tableType = "origin", tableIndex = 51, categoryName = "American Samoa", flavorText = "Connections matter when everything is separated."},
    [52] = {tableType = "origin", tableIndex = 52, categoryName = "Guam", flavorText = "You don't waste a supply run."},
    [53] = {tableType = "origin", tableIndex = 53, categoryName = "Northern Mariana Islands", flavorText = "One island leads to another. One floor does too."},
    [54] = {tableType = "origin", tableIndex = 54, categoryName = "Bermuda", flavorText = "You have heard enough stories about bad navigation to take it personally."},
    [55] = {tableType = "origin", tableIndex = 55, categoryName = "U.S. Virgin Islands", flavorText = "By the third crossing, you've got the rhythm."},
    [56] = {tableType = "origin", tableIndex = 56, categoryName = "Canada", flavorText = "Preparation is mostly knowing another layer may be necessary."},
    [57] = {tableType = "origin", tableIndex = 57, categoryName = "United Kingdom", flavorText = "The announcement has been internalized."},
    [58] = {tableType = "origin", tableIndex = 58, categoryName = "Ireland", flavorText = "You knew that was going to happen. Probably."},
    [59] = {tableType = "origin", tableIndex = 59, categoryName = "Australia", flavorText = "Worrying before impact wastes perfectly good time."},
    [60] = {tableType = "origin", tableIndex = 60, categoryName = "New Zealand", flavorText = "You have accepted that the interesting thing is never nearby."},
    [61] = {tableType = "origin", tableIndex = 61, categoryName = "Jamaica", flavorText = "Rushing and moving quickly are not the same thing."},
    [62] = {tableType = "origin", tableIndex = 62, categoryName = "Trinidad and Tobago", flavorText = "Do it once, then do the other one."},
    [63] = {tableType = "origin", tableIndex = 63, categoryName = "Bahamas", flavorText = "If you can see it cleanly, you shoot it cleanly."},
    [64] = {tableType = "origin", tableIndex = 64, categoryName = "Barbados", flavorText = "A little expenditure puts wind behind you."},
}

Catalog.Backgrounds = {
    [1] = {tableType = "background", tableIndex = 1, categoryName = "Accountant", flavorText = "You have seen too many things disappear because nobody reconciled the numbers."},
    [2] = {tableType = "background", tableIndex = 2, categoryName = "Actor", flavorText = "You know where the light is and where you're supposed to stand."},
    [3] = {tableType = "background", tableIndex = 3, categoryName = "Architect", flavorText = "You can tell which wall is going to win the argument."},
    [4] = {tableType = "background", tableIndex = 4, categoryName = "Auto Mechanic", flavorText = "You have removed worse parts under worse lighting."},
    [5] = {tableType = "background", tableIndex = 5, categoryName = "Baker", flavorText = "There is always another tray if you planned correctly."},
    [6] = {tableType = "background", tableIndex = 6, categoryName = "Barber", flavorText = "Close work does not make you nervous."},
    [7] = {tableType = "background", tableIndex = 7, categoryName = "Bartender", flavorText = "You know when somebody has had enough."},
    [8] = {tableType = "background", tableIndex = 8, categoryName = "Bookkeeper", flavorText = "The ledger will balance."},
    [9] = {tableType = "background", tableIndex = 9, categoryName = "Bus Driver", flavorText = "You have spent years enforcing invisible boundaries."},
    [10] = {tableType = "background", tableIndex = 10, categoryName = "Carpenter", flavorText = "If the fit is wrong, somebody measured wrong."},
    [11] = {tableType = "background", tableIndex = 11, categoryName = "Cashier", flavorText = "You refuse to let a remainder disappear without accounting for it."},
    [12] = {tableType = "background", tableIndex = 12, categoryName = "Chef", flavorText = "Everything useful should already be where your hand expects it."},
    [13] = {tableType = "background", tableIndex = 13, categoryName = "Childcare Worker", flavorText = "Silence from the other room is information."},
    [14] = {tableType = "background", tableIndex = 14, categoryName = "Civil Engineer", flavorText = "You think in load paths and legal crossings."},
    [15] = {tableType = "background", tableIndex = 15, categoryName = "Cleaner", flavorText = "You recognize things that should not be attached to the ceiling or floor."},
    [16] = {tableType = "background", tableIndex = 16, categoryName = "Construction Worker", flavorText = "You respect gravity because gravity does not negotiate."},
    [17] = {tableType = "background", tableIndex = 17, categoryName = "Customer Support Rep", flavorText = "You have explained the same emergency calmly more times than anyone should."},
    [18] = {tableType = "background", tableIndex = 18, categoryName = "Delivery Driver", flavorText = "The package does not care how complicated the building is."},
    [19] = {tableType = "background", tableIndex = 19, categoryName = "Dentist", flavorText = "Small moving targets are still targets."},
    [20] = {tableType = "background", tableIndex = 20, categoryName = "Graphic Designer", flavorText = "If the important thing is not obvious, the layout has failed."},
    [21] = {tableType = "background", tableIndex = 21, categoryName = "Electrician", flavorText = "You do not touch the exciting wire."},
    [22] = {tableType = "background", tableIndex = 22, categoryName = "EMT", flavorText = "Panic is data, not a plan."},
    [23] = {tableType = "background", tableIndex = 23, categoryName = "Farmer", flavorText = "You've already done half a day's work by the time danger wakes up."},
    [24] = {tableType = "background", tableIndex = 24, categoryName = "Florist", flavorText = "Some arrangements should not be jostled."},
    [25] = {tableType = "background", tableIndex = 25, categoryName = "Freelance Writer", flavorText = "Nothing creates clarity like something being due."},
    [26] = {tableType = "background", tableIndex = 26, categoryName = "Grocery Clerk", flavorText = "You notice which shelf has not been faced."},
    [27] = {tableType = "background", tableIndex = 27, categoryName = "Groundskeeper", flavorText = "You know which path everybody actually uses."},
    [28] = {tableType = "background", tableIndex = 28, categoryName = "IT Help Desk", flavorText = "Sometimes the ritual works."},
    [29] = {tableType = "background", tableIndex = 29, categoryName = "Journalist", flavorText = "One fact should point to the next one."},
    [30] = {tableType = "background", tableIndex = 30, categoryName = "Librarian", flavorText = "You have spent years locating things without raising your voice."},
    [31] = {tableType = "background", tableIndex = 31, categoryName = "Line Cook", flavorText = "This is not the hottest station you've worked."},
    [32] = {tableType = "background", tableIndex = 32, categoryName = "Mail Carrier", flavorText = "The route continues."},
    [33] = {tableType = "background", tableIndex = 33, categoryName = "Medical Assistant", flavorText = "You check the obvious things before inventing a diagnosis."},
    [34] = {tableType = "background", tableIndex = 34, categoryName = "Musician", flavorText = "The rhythm is alarming, but it is a rhythm."},
    [35] = {tableType = "background", tableIndex = 35, categoryName = "Nurse", flavorText = "You know which problem becomes fatal first."},
    [36] = {tableType = "background", tableIndex = 36, categoryName = "Office Administrator", flavorText = "You have organized worse dependencies."},
    [37] = {tableType = "background", tableIndex = 37, categoryName = "Paralegal", flavorText = "There is always a clause everybody missed."},
    [38] = {tableType = "background", tableIndex = 38, categoryName = "Pharmacist", flavorText = "You are professionally suspicious of 'a little more.'"},
    [39] = {tableType = "background", tableIndex = 39, categoryName = "Photographer", flavorText = "You know the exact cost of shaking at the wrong moment."},
    [40] = {tableType = "background", tableIndex = 40, categoryName = "Plumber", flavorText = "Pressure finds the weak connection first."},
    [41] = {tableType = "background", tableIndex = 41, categoryName = "Politician", flavorText = "You can make a hallway feel like a constituency."},
    [42] = {tableType = "background", tableIndex = 42, categoryName = "Real Estate Agent", flavorText = "You cannot sell what you cannot find."},
    [43] = {tableType = "background", tableIndex = 43, categoryName = "Receptionist", flavorText = "Everybody gets processed."},
    [44] = {tableType = "background", tableIndex = 44, categoryName = "Retail Worker", flavorText = "Against all evidence, there is one more in the back."},
    [45] = {tableType = "background", tableIndex = 45, categoryName = "Rideshare Driver", flavorText = "Recalculating."},
    [46] = {tableType = "background", tableIndex = 46, categoryName = "Social Media Manager", flavorText = "An audience changes the performance."},
    [47] = {tableType = "background", tableIndex = 47, categoryName = "Stock Trader", flavorText = "You are finally disciplined about exits."},
    [48] = {tableType = "background", tableIndex = 48, categoryName = "Teacher", flavorText = "You can make a plan comprehensible under hostile conditions."},
    [49] = {tableType = "background", tableIndex = 49, categoryName = "Telemarketer", flavorText = "Rejection is just another attempt counter."},
    [50] = {tableType = "background", tableIndex = 50, categoryName = "Therapist", flavorText = "Being observed is less powerful once you say it out loud."},
    [51] = {tableType = "background", tableIndex = 51, categoryName = "Translator", flavorText = "Meaning is usually hiding in plain sight."},
    [52] = {tableType = "background", tableIndex = 52, categoryName = "Truck Driver", flavorText = "Eventually the road becomes a state of mind."},
    [53] = {tableType = "background", tableIndex = 53, categoryName = "Warehouse Picker", flavorText = "A maze is just a warehouse without labels."},
    [54] = {tableType = "background", tableIndex = 54, categoryName = "Web Developer", flavorText = "You have strong feelings about recomputing the same thing twice."},
    [55] = {tableType = "background", tableIndex = 55, categoryName = "Welder", flavorText = "Bright light is a workplace condition."},
    [56] = {tableType = "background", tableIndex = 56, categoryName = "Barista", flavorText = "You are briefly operating above manufacturer specification."},
    [57] = {tableType = "background", tableIndex = 57, categoryName = "Dog Walker", flavorText = "You match pace automatically."},
    [58] = {tableType = "background", tableIndex = 58, categoryName = "House Painter", flavorText = "You are comfortable working right up to the edge."},
    [59] = {tableType = "background", tableIndex = 59, categoryName = "Lab Technician", flavorText = "If everything changes at once, you learn nothing."},
    [60] = {tableType = "background", tableIndex = 60, categoryName = "Museum Guide", flavorText = "You have led groups through stranger layouts."},
    [61] = {tableType = "background", tableIndex = 61, categoryName = "Personal Trainer", flavorText = "You said one more. You did not say how many times."},
    [62] = {tableType = "background", tableIndex = 62, categoryName = "Pest Control Technician", flavorText = "You have a broad definition of infestation."},
    [63] = {tableType = "background", tableIndex = 63, categoryName = "Stay-at-Home Parent", flavorText = "There is always something useful in a pocket somewhere."},
    [64] = {tableType = "background", tableIndex = 64, categoryName = "NEET", flavorText = "You have put an unreasonable number of hours into obscure movement tech."},
}

Catalog.Motives = {
    [1] = {tableType = "motive", tableIndex = 1, categoryName = "Long-Lost Lover", flavorText = "You have rehearsed this reunion enough times to know it will not go normally."},
    [2] = {tableType = "motive", tableIndex = 2, categoryName = "Sister", flavorText = "Nobody gets to imprison your sister and keep a normal workday."},
    [3] = {tableType = "motive", tableIndex = 3, categoryName = "Cousin", flavorText = "You are already composing the story that makes you sound cooler."},
    [4] = {tableType = "motive", tableIndex = 4, categoryName = "Best Friend", flavorText = "You know exactly how much grief you'll get if you're late."},
    [5] = {tableType = "motive", tableIndex = 5, categoryName = "Boss", flavorText = "This rescue is going on the résumé."},
    [6] = {tableType = "motive", tableIndex = 6, categoryName = "Employee", flavorText = "You are trying something radical: taking responsibility for staff."},
    [7] = {tableType = "motive", tableIndex = 7, categoryName = "Coworker", flavorText = "You have survived worse because somebody swapped shifts."},
    [8] = {tableType = "motive", tableIndex = 8, categoryName = "Former Roommate", flavorText = "There are unresolved financial matters."},
    [9] = {tableType = "motive", tableIndex = 9, categoryName = "Neighbor", flavorText = "You were already in the area."},
    [10] = {tableType = "motive", tableIndex = 10, categoryName = "Childhood Friend", flavorText = "You remember bicycles, summer, and a complete absence of Wardens."},
    [11] = {tableType = "motive", tableIndex = 11, categoryName = "Ex-Partner", flavorText = "This is healthier than texting."},
    [12] = {tableType = "motive", tableIndex = 12, categoryName = "Secret Admirer", flavorText = "Distance has always been your specialty."},
    [13] = {tableType = "motive", tableIndex = 13, categoryName = "Deborah Owes You $20", flavorText = "Interest has been accruing."},
    [14] = {tableType = "motive", tableIndex = 14, categoryName = "You Owe Deborah $20", flavorText = "This is an extremely elaborate repayment plan."},
    [15] = {tableType = "motive", tableIndex = 15, categoryName = "She Has Your Keys", flavorText = "You would like to go home eventually."},
    [16] = {tableType = "motive", tableIndex = 16, categoryName = "She Has Your Phone", flavorText = "You are operating under primitive conditions."},
    [17] = {tableType = "motive", tableIndex = 17, categoryName = "She Knows the Wi-Fi Password", flavorText = "Civilization has standards."},
    [18] = {tableType = "motive", tableIndex = 18, categoryName = "For the Fame", flavorText = "You have already decided which photo they should use."},
    [19] = {tableType = "motive", tableIndex = 19, categoryName = "For the Views", flavorText = "The numbers are up."},
    [20] = {tableType = "motive", tableIndex = 20, categoryName = "For the Likes", flavorText = "Validation is a combat resource now."},
    [21] = {tableType = "motive", tableIndex = 21, categoryName = "Bored", flavorText = "You said you wanted plans."},
    [22] = {tableType = "motive", tableIndex = 22, categoryName = "Lonely", flavorText = "You are aggressively solving the problem."},
    [23] = {tableType = "motive", tableIndex = 23, categoryName = "Good Samaritan", flavorText = "Somebody needed help. That was enough."},
    [24] = {tableType = "motive", tableIndex = 24, categoryName = "Born Hero", flavorText = "You have been waiting your entire life for a sentence like 'Deborah is imprisoned.'"},
    [25] = {tableType = "motive", tableIndex = 25, categoryName = "Wrong Place, Right Time", flavorText = "You were already here when the screaming started."},
    [26] = {tableType = "motive", tableIndex = 26, categoryName = "Former Warden Employee", flavorText = "You know exactly which meetings could have been emails."},
    [27] = {tableType = "motive", tableIndex = 27, categoryName = "Revenge on the Warden", flavorText = "The labyrinth is just the commute."},
    [28] = {tableType = "motive", tableIndex = 28, categoryName = "Expose the Warden", flavorText = "You brought documentation."},
    [29] = {tableType = "motive", tableIndex = 29, categoryName = "Union Solidarity", flavorText = "An injury to one is apparently a ballistic issue."},
    [30] = {tableType = "motive", tableIndex = 30, categoryName = "Civic Duty", flavorText = "You read the small print under 'community responsibilities.'"},
    [31] = {tableType = "motive", tableIndex = 31, categoryName = "Religious Calling", flavorText = "You are choosing to interpret the signs very literally."},
    [32] = {tableType = "motive", tableIndex = 32, categoryName = "A Prophecy", flavorText = "The prophecy could have included better directions."},
    [33] = {tableType = "motive", tableIndex = 33, categoryName = "A Dream", flavorText = "The ceiling was lower in the dream."},
    [34] = {tableType = "motive", tableIndex = 34, categoryName = "Déjà Vu", flavorText = "You do not remember being here. Your feet disagree."},
    [35] = {tableType = "motive", tableIndex = 35, categoryName = "A Bet", flavorText = "You are not explaining the stakes."},
    [36] = {tableType = "motive", tableIndex = 36, categoryName = "Lost a Dare", flavorText = "The group chat is never hearing you complain."},
    [37] = {tableType = "motive", tableIndex = 37, categoryName = "Community Service", flavorText = "The paperwork said 'public benefit.' It was vague."},
    [38] = {tableType = "motive", tableIndex = 38, categoryName = "Court Order", flavorText = "Failure to complete may have consequences."},
    [39] = {tableType = "motive", tableIndex = 39, categoryName = "Insurance Claim", flavorText = "This is absolutely going in the claim."},
    [40] = {tableType = "motive", tableIndex = 40, categoryName = "Bounty", flavorText = "You appreciate a clearly defined deliverable."},
    [41] = {tableType = "motive", tableIndex = 41, categoryName = "Reward Money", flavorText = "Your motivation has denominations."},
    [42] = {tableType = "motive", tableIndex = 42, categoryName = "Scientific Curiosity", flavorText = "The ethical review board has stopped returning your calls."},
    [43] = {tableType = "motive", tableIndex = 43, categoryName = "Journalistic Scoop", flavorText = "You need to be first and correct, ideally in that order."},
    [44] = {tableType = "motive", tableIndex = 44, categoryName = "Documentary Project", flavorText = "The camera is metaphorical. The commitment is not."},
    [45] = {tableType = "motive", tableIndex = 45, categoryName = "Podcast Episode", flavorText = "You already have a title and three ad breaks."},
    [46] = {tableType = "motive", tableIndex = 46, categoryName = "True-Crime Obsession", flavorText = "You have listened to enough episodes to distrust ceilings and surveillance."},
    [47] = {tableType = "motive", tableIndex = 47, categoryName = "Conspiracy Theory", flavorText = "Vindication is exhausting."},
    [48] = {tableType = "motive", tableIndex = 48, categoryName = "Midlife Crisis", flavorText = "This seemed cheaper than the other option."},
    [49] = {tableType = "motive", tableIndex = 49, categoryName = "Trying to Impress Someone", flavorText = "Confidence is easiest before the first hit."},
    [50] = {tableType = "motive", tableIndex = 50, categoryName = "Trying to Impress Deborah", flavorText = "Flowers seemed insufficient."},
    [51] = {tableType = "motive", tableIndex = 51, categoryName = "Guilt", flavorText = "You are done pretending this is somebody else's problem."},
    [52] = {tableType = "motive", tableIndex = 52, categoryName = "Redemption", flavorText = "Progress is progress."},
    [53] = {tableType = "motive", tableIndex = 53, categoryName = "Professional Courtesy", flavorText = "You recognize competent procedure even when it is shooting at you."},
    [54] = {tableType = "motive", tableIndex = 54, categoryName = "She Saved You Once", flavorText = "You remember who showed up."},
    [55] = {tableType = "motive", tableIndex = 55, categoryName = "She Fed Your Cat", flavorText = "The cat was very clear about expectations."},
    [56] = {tableType = "motive", tableIndex = 56, categoryName = "She Has Your Cat", flavorText = "This has become non-negotiable."},
    [57] = {tableType = "motive", tableIndex = 57, categoryName = "She Has Your Dog", flavorText = "There is no committee phase."},
    [58] = {tableType = "motive", tableIndex = 58, categoryName = "She Has the Password", flavorText = "Two-factor authentication has gone too far."},
    [59] = {tableType = "motive", tableIndex = 59, categoryName = "She Knows What You Did", flavorText = "You need this conversation to happen privately."},
    [60] = {tableType = "motive", tableIndex = 60, categoryName = "You Need a Favor", flavorText = "You are building goodwill at unsustainable scale."},
    [61] = {tableType = "motive", tableIndex = 61, categoryName = "You Want an Adventure", flavorText = "You specifically asked for something memorable."},
    [62] = {tableType = "motive", tableIndex = 62, categoryName = "You Missed Your Exit", flavorText = "At some point the wrong road becomes the trip."},
    [63] = {tableType = "motive", tableIndex = 63, categoryName = "Everyone Else Was Busy", flavorText = "The group chat produced one volunteer."},
    [64] = {tableType = "motive", tableIndex = 64, categoryName = "No Particular Reason", flavorText = "You were asked why. You did not have an answer."},
}

Catalog.MasculineFirstNames = {
    [1] = "Adam",
    [2] = "Adrian",
    [3] = "Alex",
    [4] = "Andrew",
    [5] = "Anthony",
    [6] = "Arthur",
    [7] = "Benjamin",
    [8] = "Blake",
    [9] = "Brandon",
    [10] = "Caleb",
    [11] = "Cameron",
    [12] = "Charles",
    [13] = "Christopher",
    [14] = "Connor",
    [15] = "Daniel",
    [16] = "David",
    [17] = "Declan",
    [18] = "Derek",
    [19] = "Dylan",
    [20] = "Edward",
    [21] = "Eli",
    [22] = "Ethan",
    [23] = "Evan",
    [24] = "Felix",
    [25] = "Finn",
    [26] = "Gabriel",
    [27] = "George",
    [28] = "Graham",
    [29] = "Henry",
    [30] = "Ian",
    [31] = "Isaac",
    [32] = "Jack",
    [33] = "Jacob",
    [34] = "James",
    [35] = "Jason",
    [36] = "Joel",
    [37] = "Jonah",
    [38] = "Jonathan",
    [39] = "Jordan",
    [40] = "Joseph",
    [41] = "Julian",
    [42] = "Kai",
    [43] = "Leo",
    [44] = "Liam",
    [45] = "Logan",
    [46] = "Lucas",
    [47] = "Marcus",
    [48] = "Martin",
    [49] = "Matthew",
    [50] = "Miles",
    [51] = "Nathan",
    [52] = "Nicholas",
    [53] = "Noah",
    [54] = "Oliver",
    [55] = "Owen",
    [56] = "Patrick",
    [57] = "Peter",
    [58] = "Ryan",
    [59] = "Samuel",
    [60] = "Scott",
    [61] = "Simon",
    [62] = "Thomas",
    [63] = "Victor",
    [64] = "William",
}

Catalog.FeminineFirstNames = {
    [1] = "Abigail",
    [2] = "Alexandra",
    [3] = "Alice",
    [4] = "Alyssa",
    [5] = "Amelia",
    [6] = "Anna",
    [7] = "Audrey",
    [8] = "Ava",
    [9] = "Bethany",
    [10] = "Brooke",
    [11] = "Camila",
    [12] = "Caroline",
    [13] = "Charlotte",
    [14] = "Chloe",
    [15] = "Claire",
    [16] = "Daisy",
    [17] = "Danielle",
    [18] = "Eleanor",
    [19] = "Elena",
    [20] = "Elizabeth",
    [21] = "Ella",
    [22] = "Emily",
    [23] = "Emma",
    [24] = "Erin",
    [25] = "Eva",
    [26] = "Fiona",
    [27] = "Gabrielle",
    [28] = "Grace",
    [29] = "Hannah",
    [30] = "Hazel",
    [31] = "Isabel",
    [32] = "Isla",
    [33] = "Jasmine",
    [34] = "Julia",
    [35] = "Katherine",
    [36] = "Kayla",
    [37] = "Lena",
    [38] = "Lily",
    [39] = "Lucy",
    [40] = "Maya",
    [41] = "Megan",
    [42] = "Mia",
    [43] = "Naomi",
    [44] = "Natalie",
    [45] = "Nora",
    [46] = "Olivia",
    [47] = "Paige",
    [48] = "Rachel",
    [49] = "Rebecca",
    [50] = "Riley",
    [51] = "Rose",
    [52] = "Ruby",
    [53] = "Samantha",
    [54] = "Sarah",
    [55] = "Sophie",
    [56] = "Stella",
    [57] = "Tessa",
    [58] = "Valerie",
    [59] = "Victoria",
    [60] = "Violet",
    [61] = "Willow",
    [62] = "Zoe",
    [63] = "Ariana",
    [64] = "Madeline",
}

Catalog.Surnames = {
    [1] = "Adams",
    [2] = "Baker",
    [3] = "Bennett",
    [4] = "Brooks",
    [5] = "Brown",
    [6] = "Campbell",
    [7] = "Carter",
    [8] = "Clark",
    [9] = "Collins",
    [10] = "Cooper",
    [11] = "Davis",
    [12] = "Edwards",
    [13] = "Evans",
    [14] = "Fisher",
    [15] = "Foster",
    [16] = "Garcia",
    [17] = "Gray",
    [18] = "Green",
    [19] = "Hall",
    [20] = "Harris",
    [21] = "Hayes",
    [22] = "Hill",
    [23] = "Howard",
    [24] = "Hughes",
    [25] = "Jackson",
    [26] = "James",
    [27] = "Jenkins",
    [28] = "Johnson",
    [29] = "Kelly",
    [30] = "King",
    [31] = "Lee",
    [32] = "Lewis",
    [33] = "Martin",
    [34] = "Mason",
    [35] = "Miller",
    [36] = "Mitchell",
    [37] = "Moore",
    [38] = "Morgan",
    [39] = "Morris",
    [40] = "Murphy",
    [41] = "Nelson",
    [42] = "Parker",
    [43] = "Patel",
    [44] = "Perry",
    [45] = "Phillips",
    [46] = "Price",
    [47] = "Reed",
    [48] = "Reyes",
    [49] = "Richardson",
    [50] = "Rivera",
    [51] = "Roberts",
    [52] = "Robinson",
    [53] = "Rogers",
    [54] = "Ross",
    [55] = "Russell",
    [56] = "Scott",
    [57] = "Stewart",
    [58] = "Taylor",
    [59] = "Thomas",
    [60] = "Turner",
    [61] = "Walker",
    [62] = "Ward",
    [63] = "White",
    [64] = "Young",
}

Catalog.Nicknames = {
    [1] = "The Knife",
    [2] = "Fast Hands",
    [3] = "Little Buddy",
    [4] = "Big Deal",
    [5] = "Lucky",
    [6] = "The Professor",
    [7] = "Sideways",
    [8] = "Hot Sauce",
    [9] = "Two-Step",
    [10] = "The Accountant",
    [11] = "No Refunds",
    [12] = "Bluebird",
    [13] = "Switchback",
    [14] = "Short Stack",
    [15] = "Long Shot",
    [16] = "Pocket Change",
    [17] = "The Mayor",
    [18] = "Corkscrew",
    [19] = "Night Shift",
    [20] = "Lunchbox",
    [21] = "The Goose",
    [22] = "Spare Parts",
    [23] = "Three Times",
    [24] = "Half Pint",
    [25] = "Dead Serious",
    [26] = "The Tourist",
    [27] = "Quick Draw",
    [28] = "Slow Burn",
    [29] = "Wrong Way",
    [30] = "Good News",
    [31] = "The Closer",
    [32] = "Paperclip",
    [33] = "Big Tuna",
    [34] = "Tiny Thunder",
    [35] = "The Intern",
    [36] = "Lefty",
    [37] = "Righty",
    [38] = "Second Shift",
    [39] = "Cold Coffee",
    [40] = "The Hammer",
    [41] = "Soft Shoes",
    [42] = "Hard Luck",
    [43] = "The Volunteer",
    [44] = "Redline",
    [45] = "The Witness",
    [46] = "Breadcrumbs",
    [47] = "The Customer",
    [48] = "Plan B",
    [49] = "The Local",
    [50] = "High Mileage",
    [51] = "Small Talk",
    [52] = "The Specialist",
    [53] = "No Problem",
    [54] = "The Substitute",
    [55] = "Five Bucks",
    [56] = "Headcount",
    [57] = "Floor Two",
    [58] = "The Reroute",
    [59] = "After Hours",
    [60] = "Good Enough",
    [61] = "The Legend",
    [62] = "The Backup",
    [63] = "One More",
    [64] = "Absolutely Not",
}

Catalog.LevelOneOrdinaryFeats = {
    CON_REGEN_11 = {featId = "CON_REGEN_11", displayName = "Second Wind", governingAbilities = {"con"}, abilityRequirements = {con = 12}, prerequisiteFeatIds = {}, requiredCapabilityTags = {}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "Enables passive Health Regeneration if the actor did not already have it. After 5.0 continuous seconds without taking effective damage, regenerate toward 11% of current MaxHP at BaseHealthRegen = 1.0% MaxHP/second × ConRegenMultiplier. Regeneration stops immediately at 11% MaxHP or when damage is taken. It never restores temporary Tetris overfill."}, directorBaseWeight = 1.0, eligibilityText = "CON 12", actorText = "Heroes, human Soldiers, AI"},
    DEX_EXPLODE_D10 = {featId = "DEX_EXPLODE_D10", displayName = "Perfect Ten", governingAbilities = {"dex"}, abilityRequirements = {dex = 12}, prerequisiteFeatIds = {}, requiredCapabilityTags = {"d10_damage"}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "The actor's ordinary player-owned/actor-owned d10 damage dice become exploding dice. A fresh d10 explodes only on natural 10. Continuation d10s use threshold max(2, 10 - BoomShift). Every explosion adds another d10 to the same damage chain and is subject to the universal 32-die safety cap."}, directorBaseWeight = 1.0, eligibilityText = "DEX 12", actorText = "Non-Rogue heroes, human Soldiers, and AI with d10 damage rolls"},
    DEX_FAST_RELOAD = {featId = "DEX_FAST_RELOAD", displayName = "Quick Reload", governingAbilities = {"dex"}, abilityRequirements = {dex = 12}, prerequisiteFeatIds = {}, requiredCapabilityTags = {"reloadable_firearm"}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "Sets ReloadTimeMultiplier = 0.80 for ordinary reloadable weapons. It does not shorten SMG overheat recovery, AR2 targeting-laser delay, Magic cooldowns, enemy authored telegraphs, or other non-reload timers."}, directorBaseWeight = 1.0, eligibilityText = "DEX 12", actorText = "Player-controlled heroes/human Soldiers; AI only if its authored weapon actually uses the shared reload authority"},
    INT_AMMO_FLOOR_44 = {featId = "INT_AMMO_FLOOR_44", displayName = "Field Supply", governingAbilities = {"int"}, abilityRequirements = {int = 12}, prerequisiteFeatIds = {}, requiredCapabilityTags = {"firearm"}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "Raises the actor's ordinary regenerative firearm AmmoRegenFloorFraction from 0.33 to 0.44. For each eligible owned family, AmmoRegenFloorRounds = ceil(MaxFamilyCapacity × 0.44). The feat changes only how far free regeneration may refill; it does not accelerate the family's existing per-round regeneration cadence, shorten its no-fire eligibility delay, increase maximum ammunition capacity, create an unowned weapon, or make Grenades/AR2 secondary ammunition regenerative."}, directorBaseWeight = 1.0, eligibilityText = "INT 12", actorText = "Player-controlled heroes and human Soldiers only when they possess at least one ordinary firearm family that uses the shared ammunition-regeneration authority"},
    DEX_RATE_OF_FIRE_1 = {featId = "DEX_RATE_OF_FIRE_1", displayName = "Hair Trigger", governingAbilities = {"dex"}, abilityRequirements = {dex = 12}, prerequisiteFeatIds = {}, requiredCapabilityTags = {"firearm"}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "Sets RateOfFireMultiplier = 1.10. For eligible ordinary firearm primary attacks, NextPrimaryAttackInterval = BasePrimaryAttackInterval / RateOfFireMultiplier. It changes trigger/attack opportunity cadence only: it does not shorten reloads, Magic cooldowns, SMG cooling or 2-second overheat lockout, AR2 targeting-laser duration, internal AR2 three-shot spacing, Magnum free-projectile burst spacing, or enemy telegraph duration."}, directorBaseWeight = 1.0, eligibilityText = "DEX 12", actorText = "Heroes, human Soldiers, and AI whose equipped/authored ordinary firearm uses the shared attack-cadence authority"},
    DEX_BURSTER_1 = {featId = "DEX_BURSTER_1", displayName = "Extra Round", governingAbilities = {"dex"}, abilityRequirements = {dex = 12}, prerequisiteFeatIds = {}, requiredCapabilityTags = {"multi_fire_burst"}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "BurstBonusRounds = 1. Whenever an authored attack event is already a legal multi-fire burst before feat processing, add one additional round/projectile to that burst. This feat never creates a burst from a single-fire attack and never treats exploding dice, Shotgun pellets, penetration, chained Magic projectiles, or unrelated extra-projectile procs as bursts."}, directorBaseWeight = 1.0, eligibilityText = "DEX 12", actorText = "Heroes, human Soldiers, and AI actors with at least one weapon attack explicitly tagged multiFireBurst"},
    STR_CROWBAR_D6 = {featId = "STR_CROWBAR_D6", displayName = "Bash", governingAbilities = {"str"}, abilityRequirements = {str = 12}, prerequisiteFeatIds = {}, requiredCapabilityTags = {"crowbar"}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "The Crowbar/Long-Sword-family base damage die becomes 1d6 instead of 1d3. Every successful nonlethal hit also applies a 168-world-unit physical push through LOD.Pushback. The d6 uses the universal exploding-d6 rule. If the push is stopped by valid architecture, ordinary wall crush remains 1d3 unless another feat changes that crush."}, directorBaseWeight = 1.0, eligibilityText = "STR 12", actorText = "Player-controlled heroes/human Soldiers with Crowbar/melee-family access"},
    WIS_HERO_OF_LEGEND = {featId = "WIS_HERO_OF_LEGEND", displayName = "Hero of Legend", governingAbilities = {"wis"}, abilityRequirements = {wis = 15}, prerequisiteFeatIds = {}, requiredCapabilityTags = {"crowbar"}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {"crowbar", "magic"}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "At CurrentHP >= min(100, MaxHP), a legitimate Crowbar/Long-Sword-family primary swing launches one glowing Crowbar model from the attacker's arm if no other Hero of Legend projectile is active anywhere. It travels at 620 world units per second for max(1, the attacker's WIS bonus) maze cells and stops at the first blocking surface or eligible hostile after ordinary melee reach. A hit resolves the current Crowbar die as non-elemental Magic damage through the WIS Magic multiplier. It costs no ammunition or Magic, cannot push, wall-crush, satisfy melee/firearm triggers, pierce bodies, or recursively emit another projectile."}, directorBaseWeight = 1.0, eligibilityText = "WIS 15", actorText = "Player-controlled heroes/human Soldiers with Crowbar/Long-Sword-family access"},
    STR_KNOCKBACK_1 = {featId = "STR_KNOCKBACK_1", displayName = "Pusher", governingAbilities = {"str"}, abilityRequirements = {str = 12}, prerequisiteFeatIds = {}, requiredCapabilityTags = {"pushable_weapon"}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "Sets WeaponKnockbackProcChance = 0.25 and WeaponKnockbackProcDistance = 168 world units. After a successful nonlethal ordinary weapon hit resolves its damage against an eligible pushable hostile, make at most one deterministic Pusher-family proc roll for that resolved target-hit event. Shotgun makes one roll per damaged target per shell after pellet aggregation; each true projectile in an authored multi-projectile attack may create its own target-hit event, but individual pellets, damage dice, penetration-added dice, and Boomchain continuations never create additional proc rolls by themselves. On success, if the hit has no authored physical push, add a 168-unit physical push through LOD.Pushback; if it already has an authored physical push, add +168 world units to that event's requested push distance before compatible multipliers and collision resolution. On failure, a pre-existing push still resolves normally. Pusher-family proc generation also uses a shared per-attacker/per-target success cooldown: PusherProcTargetCooldownSeconds = 0.50. While that cooldown is active for the same attacker-target pair, later hits make no Pusher-family proc roll, although any authored push on those hits still resolves normally. A successful Pusher-family proc starts the 0.50-second cooldown; a failed eligible roll does not. Different targets track cooldown independently. Separately and regardless of whether the proc succeeded, this actor's ordinary physical-push wall-slam/wall-crush base die becomes 1d8 instead of the shared 1d3. Pusher-family d8 wall-slam dice are tagged classExplosionImmune=true. They are deliberately non-exploding for every class and cannot be made explosive by Rogue mastery, Eight Is Enough, equipment, or another ordinary explosion-enabler; unlocking explosion inside this family is reserved for Space Hog. The knockback proc is a utility proc, not a damage die, and is not Luck-Ring eligible unless a later rule explicitly says otherwise."}, directorBaseWeight = 1.0, eligibilityText = "STR 12", actorText = "Heroes, human Soldiers, and AI with at least one ordinary weapon attack capable of damaging a pushable hostile"},
    CON_STEADFAST = {featId = "CON_STEADFAST", displayName = "Hard to Move", governingAbilities = {"con"}, abilityRequirements = {con = 12}, prerequisiteFeatIds = {}, requiredCapabilityTags = {}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "Incoming ordinary hit-stun duration and non-scripted push displacement are each multiplied by 0.75. Authored boss mechanics that explicitly ignore resistance remain exceptions."}, directorBaseWeight = 1.0, eligibilityText = "CON 12", actorText = "Heroes, human Soldiers, AI"},
    CON_RUSSIAN_ASSET = {featId = "CON_RUSSIAN_ASSET", displayName = "Russian Asset", governingAbilities = {"int"}, abilityRequirements = {int = 13}, prerequisiteFeatIds = {}, requiredCapabilityTags = {"tetris"}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "Doubles all temporary HP overfill earned from qualifying Tetris line-clear rewards: TetrisOverfillMultiplier = 2.0, so the baseline single/double/triple/quad rewards become +20/+60/+100/+160 HP and all accumulated qualifying Tetris reward is doubled before being applied. This reward multiplier applies to both death Tetris and post-rescue/victory Tetris. Separately, only for death Tetris, DeathTetrisMaxSeconds increases from the normally hidden 60-second hard cap to 120 seconds. Russian Asset does not change the mandatory 20-second death/respawn lockout, does not delay the moment F becomes available to respawn, does not require the player to remain dead for 120 seconds, and does not extend post-rescue/victory Tetris beyond its ordinary 20-second duration. Pressing F at any eligible time after the 20-second minimum still immediately finalizes the current death-Tetris score and respawns normally."}, directorBaseWeight = 1.0, eligibilityText = "INT 13", actorText = "Player-controlled cooperative heroes with Tetris access"},
    DEX_SMG_COLD_HANDS_1 = {featId = "DEX_SMG_COLD_HANDS_1", displayName = "Cold Hands", governingAbilities = {"dex"}, abilityRequirements = {dex = 12}, prerequisiteFeatIds = {}, requiredCapabilityTags = {"smg"}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "Sets SMGHeatSuppressionChance = 0.11 and SMGOverheatThreshold = 8 heat. On every successfully fired SMG round, before that round adds its normal one shot-equivalent of heat, the server makes one deterministic heat-suppression roll from the dedicated SMG-heat substream. Cold Hands heat-suppression rolls are not Luck-Ring eligible and cannot be rerolled or advantaged unless a later feat explicitly says otherwise. On success, that round adds 0 heat; on failure, it adds the ordinary +1 heat. The SMG overheats when accumulated heat reaches 8 rather than the baseline 6. Damage, ammunition consumption, fire rate, sub-threshold cooling, visual/audio heat stages, and the fixed 2.0-second overheat lockout are unchanged."}, directorBaseWeight = 1.0, eligibilityText = "DEX 12", actorText = "Player-controlled heroes and human Soldiers who possess/use the SMG"},
    INT_MANA_BARRIER_1 = {featId = "INT_MANA_BARRIER_1", displayName = "Mana Barrier", governingAbilities = {"int"}, abilityRequirements = {int = 12}, prerequisiteFeatIds = {}, requiredCapabilityTags = {"magic_pool"}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "Sets ManaBarrierFeatDiversionFraction = 0.15. HPToMagicDiversionFraction = WizardClassHPToMagicDiversionFraction + ManaBarrierFeatDiversionFraction, so non-Wizards receive 15% total from this feat while Wizards add the feat's 15 percentage points to their innate 2%-per-Level diversion. After an incoming damage event has completed all ordinary damage resolution, including attack dice/Boomchains, weakness/resistance/immunity handling, CON DamageResistancePerDie, and other authored mitigation or amplification, but immediately before HP is removed, define ResolvedHPDamage as the whole-number HP damage that would otherwise be applied. DesiredMagicDiversion = floor(ResolvedHPDamage × HPToMagicDiversionFraction + 0.5). ActualMagicDiversion = min(DesiredMagicDiversion, floor(CurrentMagic)). Reduce CurrentMagic by ActualMagicDiversion and reduce the HP loss by the same amount: FinalHPDamage = ResolvedHPDamage - ActualMagicDiversion. One diverted HP therefore deals exactly 1 point of Magic damage instead. Magic cannot fall below 0. This diversion authority is automatic whenever HPToMagicDiversionFraction > 0, whether supplied by the Wizard class passive, the Mana Barrier feat family, or both, and applies to ordinary damage events from actors or the environment, including damage to temporary Tetris overfill, but not direct kill commands, non-damage death states, or effects explicitly tagged ignoreManaBarrier. HP-to-Magic diversion loss is classified as Magic damage, not voluntary Magic spending, so spend/cast triggers do not fire merely because the barrier absorbed damage. If the barrier reduces Magic to 0, normal zero-Magic consequences still occur, including forced minimap closure; ordinary regeneration rules then govern recovery."}, directorBaseWeight = 1.0, eligibilityText = "INT 12", actorText = "Heroes, human Soldiers, Magic-using AI"},
    INT_MANA_SPRING = {featId = "INT_MANA_SPRING", displayName = "Mana Spring", governingAbilities = {"int"}, abilityRequirements = {int = 12}, prerequisiteFeatIds = {}, requiredCapabilityTags = {"magic_pool"}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "Whenever Magic reaches 0, the next time regeneration becomes legally permitted the actor receives a 1.50 multiplier to its already INT-scaled Magic regeneration for 4.0 seconds. The timer does not run and no regeneration occurs while the minimap or another regeneration-suppressing sustained effect remains active."}, directorBaseWeight = 1.0, eligibilityText = "INT 12", actorText = "Heroes, human Soldiers, Magic-using AI"},
    WIS_SURVEYOR = {featId = "WIS_SURVEYOR", displayName = "Surveyor", governingAbilities = {"wis"}, abilityRequirements = {wis = 12}, prerequisiteFeatIds = {}, requiredCapabilityTags = {"minimap"}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "Adds +4 to BreadcrumbCells after the normal WIS formula. The additional route length may display only information permitted by the current dungeon's map-degradation tier and can never leak a hidden card, gate, stair, objective, or other forbidden topology."}, directorBaseWeight = 1.0, eligibilityText = "WIS 12", actorText = "Heroes and human Soldiers with minimap access"},
    WIS_SPELLWARD = {featId = "WIS_SPELLWARD", displayName = "Spellward", governingAbilities = {"wis"}, abilityRequirements = {wis = 12}, prerequisiteFeatIds = {}, requiredCapabilityTags = {}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "Adds +2 to MagicSave against explicitly resistible magical effects."}, directorBaseWeight = 1.0, eligibilityText = "WIS 12", actorText = "Heroes, human Soldiers, AI"},
    WIS_SIXTH_SENSE = {featId = "WIS_SIXTH_SENSE", displayName = "Sixth Sense", governingAbilities = {"wis"}, abilityRequirements = {wis = 12}, prerequisiteFeatIds = {}, requiredCapabilityTags = {"cooperative_hero"}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "Sixth Sense grants three personal perception effects. First, the owner can visually perceive any entity whose authoritative state includes invisible=true. Invisibility is a reusable shared entity-state primitive rather than a Watcher-specific exception: Watchers use it now, and future enemies, effects, or actors may use the same state. An invisible entity is rendered only for the owning client as a clearly readable translucent silhouette/outline at its true current world position whenever that entity would otherwise satisfy ordinary world visibility and line-of-sight rules if invisibility were ignored. Second, Sixth Sense grants Nearby Hostile Sense: every living hostile entity on the owner's current floor whose cell-coordinate distance is within 2 grid cells is rendered to that owner as a readable through-geometry outline even when intervening walls or props block line of sight. For this sensor, NearbyCellDistance = max(abs(enemyCellX-ownerCellX), abs(enemyCellY-ownerCellY)); the effect applies when NearbyCellDistance <= 2 and floorId matches. This local 5x5-cell neighborhood intentionally ignores wall connectivity and closed-gate edges for perception only. Invisible hostiles within that neighborhood are also revealed by the same outline. Third, Sixth Sense grants Watcher Motion Sense: whenever a living Watcher is in its authoritative moving/locomotion state, each Sixth Sense owner on the same floor receives a private 3D positional Watcher movement sound attached to that Watcher's true current position. This cue plays whether the Watcher is visible or invisible and does not require line of sight; ordinary spatial attenuation provides direction and proximity, so a distant Watcher does not become an all-floor audio beacon. The cue starts when authoritative Watcher locomotion begins and stops when locomotion stops, the Watcher dies/despawns, the player changes floor, or Sixth Sense is no longer active. The movement sound is transmitted/rendered only for eligible Sixth Sense owners; players without the feat receive no such sound event. These effects create no minimap marker, breadcrumb, directional arrow, nameplate through the world, aim assistance, target lock, ballistic permission through geometry, AI aggro knowledge, or interaction permission. Sixth Sense never changes an entity's invisible state, cloak duration, AI/state machine, collision, targetability rules, or visibility to any other player; players without the feat perceive the entity normally. The server authoritatively determines feat ownership, invisible state, hostility, floor, cell coordinates, and Watcher locomotion state; owning clients render only authorized silhouettes and private Watcher movement audio. FeatDirector may offer Sixth Sense whenever the actor is a cooperative hero who meets WIS 12; Watchers or any other invisibility-using enemy need not currently be present because the 2-cell hostile-sense effect is independently useful."}, directorBaseWeight = 1.0, eligibilityText = "WIS 12", actorText = "Cooperative heroes"},
    CHA_HITSTUN_1 = {featId = "CHA_HITSTUN_1", displayName = "Unnerving Presence", governingAbilities = {"cha"}, abilityRequirements = {cha = 12}, prerequisiteFeatIds = {}, requiredCapabilityTags = {"hit_stun_source"}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "After the normal ChaHitStunInflictMultiplier is calculated, multiply eligible hit stun inflicted by this actor by 1.10. This applies once per resolved target hit/event, not once per pellet or sub-hit, and remains subject to the ordinary retrigger guard, resistance, anti-stunlock rules, and hard caps."}, directorBaseWeight = 1.0, eligibilityText = "CHA 12", actorText = "Heroes, human Soldiers, AI with an eligible hit-stun source"},
    CHA_MENACE_1 = {featId = "CHA_MENACE_1", displayName = "Menacing", governingAbilities = {"cha"}, abilityRequirements = {cha = 12}, prerequisiteFeatIds = {}, requiredCapabilityTags = {}, incompatibleFeatIds = {}, allowedActorTypes = {"hero"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = true, effectHandlerId = "gate_b_feat_ownership", effectParams = {description = "Adds +2 to MoraleDC whenever this actor is the credited attacker for a Morale check."}, directorBaseWeight = 1.0, eligibilityText = "CHA 12", actorText = "Heroes, human Soldiers, AI"},
}

Catalog.FallbackFeats = {
    FALLBACK_STR = {featId = "FALLBACK_STR", displayName = "Put Your Back Into It", governingAbilities = {"str"}, abilityRequirements = {}, prerequisiteFeatIds = {}, requiredCapabilityTags = {}, incompatibleFeatIds = {}, allowedActorTypes = {"hero", "human_soldier", "ai"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = false, repeatableFallback = true, effectHandlerId = "fallback_ability_delta", effectParams = {ability = "str", amount = 1, description = "Adds +1 permanent featAbilityDelta.str. Repeatable across later feat opportunities until intrinsic FeatQualification STR reaches 30."}, directorBaseWeight = 1.0, eligibilityText = "FeatQualification STR < 30", actorText = "Heroes, human Soldiers, AI"},
    FALLBACK_DEX = {featId = "FALLBACK_DEX", displayName = "Light Feet", governingAbilities = {"dex"}, abilityRequirements = {}, prerequisiteFeatIds = {}, requiredCapabilityTags = {}, incompatibleFeatIds = {}, allowedActorTypes = {"hero", "human_soldier", "ai"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = false, repeatableFallback = true, effectHandlerId = "fallback_ability_delta", effectParams = {ability = "dex", amount = 1, description = "Adds +1 permanent featAbilityDelta.dex. Repeatable across later feat opportunities until intrinsic FeatQualification DEX reaches 30."}, directorBaseWeight = 1.0, eligibilityText = "FeatQualification DEX < 30", actorText = "Heroes, human Soldiers, AI"},
    FALLBACK_CON = {featId = "FALLBACK_CON", displayName = "Tough It Out", governingAbilities = {"con"}, abilityRequirements = {}, prerequisiteFeatIds = {}, requiredCapabilityTags = {}, incompatibleFeatIds = {}, allowedActorTypes = {"hero", "human_soldier", "ai"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = false, repeatableFallback = true, effectHandlerId = "fallback_ability_delta", effectParams = {ability = "con", amount = 1, description = "Adds +1 permanent featAbilityDelta.con. Repeatable across later feat opportunities until intrinsic FeatQualification CON reaches 30."}, directorBaseWeight = 1.0, eligibilityText = "FeatQualification CON < 30", actorText = "Heroes, human Soldiers, AI"},
    FALLBACK_INT = {featId = "FALLBACK_INT", displayName = "Quick Study", governingAbilities = {"int"}, abilityRequirements = {}, prerequisiteFeatIds = {}, requiredCapabilityTags = {}, incompatibleFeatIds = {}, allowedActorTypes = {"hero", "human_soldier", "ai"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = false, repeatableFallback = true, effectHandlerId = "fallback_ability_delta", effectParams = {ability = "int", amount = 1, description = "Adds +1 permanent featAbilityDelta.int. Repeatable across later feat opportunities until intrinsic FeatQualification INT reaches 30."}, directorBaseWeight = 1.0, eligibilityText = "FeatQualification INT < 30", actorText = "Heroes, human Soldiers, AI"},
    FALLBACK_WIS = {featId = "FALLBACK_WIS", displayName = "Keep Your Wits", governingAbilities = {"wis"}, abilityRequirements = {}, prerequisiteFeatIds = {}, requiredCapabilityTags = {}, incompatibleFeatIds = {}, allowedActorTypes = {"hero", "human_soldier", "ai"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = false, repeatableFallback = true, effectHandlerId = "fallback_ability_delta", effectParams = {ability = "wis", amount = 1, description = "Adds +1 permanent featAbilityDelta.wis. Repeatable across later feat opportunities until intrinsic FeatQualification WIS reaches 30."}, directorBaseWeight = 1.0, eligibilityText = "FeatQualification WIS < 30", actorText = "Heroes, human Soldiers, AI"},
    FALLBACK_CHA = {featId = "FALLBACK_CHA", displayName = "Make an Impression", governingAbilities = {"cha"}, abilityRequirements = {}, prerequisiteFeatIds = {}, requiredCapabilityTags = {}, incompatibleFeatIds = {}, allowedActorTypes = {"hero", "human_soldier", "ai"}, requiredSubsystemTags = {}, synergyTags = {}, oneRank = false, repeatableFallback = true, effectHandlerId = "fallback_ability_delta", effectParams = {ability = "cha", amount = 1, description = "Adds +1 permanent featAbilityDelta.cha. Repeatable across later feat opportunities until intrinsic FeatQualification CHA reaches 30."}, directorBaseWeight = 1.0, eligibilityText = "FeatQualification CHA < 30", actorText = "Heroes, human Soldiers, AI"},
}

return Catalog
