LOD = LOD or {}
LOD.RPG = LOD.RPG or {}

local RPG = LOD.RPG
local Catalog = RPG.IdentityCatalog
local Feats = Catalog and (Catalog.OrdinaryFeats or Catalog.LevelOneOrdinaryFeats)
local Effects = RPG.FeatEffectSystem
local Rules = LOD.RPGAbilityRules
local Progression = LOD.CharacterProgressionSystem
local Validation = LOD.RPGValidation
if not Feats or not Effects or not Rules or not Progression then return end

local SOURCE_REVISION = "ANLCKQlqd7CuK8mqO8bD6YLSczpkCCbzvF_CuSWwh7tZahxeualxoHhhteJPwzEODy4h7eRO3dVCIqKnCRDqh7Khd3tSntD1CNYK-SRLVg"
local BASE_MAGNUM_HOLD_SECONDS = 0.50
local DEADEYE_HOLD_SECONDS = 0.35
local BASE_MELEE_REACH = 96
local LONG_REACH_MULTIPLIER = 1.25
local BASE_DEATH_TETRIS_SECONDS = 60
local RUSSIAN_ASSET_DEATH_TETRIS_SECONDS = 120
local RUSSIAN_ASSET_REWARD_MULTIPLIER = 2
local SPRING_HEEL_HEIGHT_MULTIPLIER = 2
local SPRING_HEEL_IMPULSE_MULTIPLIER = math.sqrt(SPRING_HEEL_HEIGHT_MULTIPLIER)

Effects.SingletonConfig = {
    sourceRevision = SOURCE_REVISION,
    baseMagnumHoldSeconds = BASE_MAGNUM_HOLD_SECONDS,
    baseMeleeReach = BASE_MELEE_REACH,
    longReachMultiplier = LONG_REACH_MULTIPLIER,
    baseDeathTetrisSeconds = BASE_DEATH_TETRIS_SECONDS,
    russianAssetDeathTetrisSeconds = RUSSIAN_ASSET_DEATH_TETRIS_SECONDS,
    russianAssetRewardMultiplier = RUSSIAN_ASSET_REWARD_MULTIPLIER,
    springHeelHeightMultiplier = SPRING_HEEL_HEIGHT_MULTIPLIER,
    springHeelImpulseMultiplier = SPRING_HEEL_IMPULSE_MULTIPLIER
}
Effects.SingletonStats = Effects.SingletonStats or {
    jumpAttempts = 0,
    jumpBoosts = 0,
    lastJumpHeight = 0,
    lastJumpMultiplier = 1,
    lastJumpImpulse = 0,
    lastJumpAddedImpulse = 0,
    baselineJumpHeight = 0,
    lastMeleeReach = 0,
    meleeSwings = 0,
    expectedEnabled = false
}
Effects.SpringHeelTraces = Effects.SpringHeelTraces
    or setmetatable({}, {__mode = "k"})

local function singletonDefinition(id, name, ability, requirement, capability, actors,
    family, handler, params, eligibility)
    return {
        featId = id,
        displayName = name,
        featFamilyId = family,
        rankIndex = 1,
        replacesLowerRank = false,
        repeatableFallback = false,
        governingAbilities = {ability},
        abilityRequirements = {[ability] = requirement},
        prerequisiteFeatIds = {},
        requiredCapabilityTags = capability and {capability} or {},
        incompatibleFeatIds = {},
        allowedActorTypes = actors,
        requiredSubsystemTags = {},
        synergyTags = {family},
        oneRank = true,
        effectHandlerId = handler,
        effectParams = params,
        directorBaseWeight = 1.0,
        eligibilityText = eligibility,
        actorText = params.actorText
    }
end

Feats.DEX_SPRING_HEEL = singletonDefinition(
    "DEX_SPRING_HEEL", "Spring Heel", "dex", 13, nil,
    {"hero", "human_soldier"}, "dex_spring_heel", "spring_heel", {
        jumpHeightMultiplier = SPRING_HEEL_HEIGHT_MULTIPLIER,
        takeoffImpulseMultiplier = SPRING_HEEL_IMPULSE_MULTIPLIER,
        actorText = "Player-controlled heroes and human Soldiers only",
        description = "Doubles the apex height of every voluntary jump generated by the actor, including ordinary ground jump and Cloud Step's feat-granted second jump. Under unchanged gravity, takeoff vertical impulse is scaled to achieve 2.0x baseline jump height. Push, knockback, falls, scripted relocation, ladders, stairs, and other non-jump movement are unchanged; anti-top, gate, ceiling, and progression blockers remain authoritative."
    }, "DEX 13")

Feats.DEX_MAGNUM_DEADEYE = singletonDefinition(
    "DEX_MAGNUM_DEADEYE", "Deadeye", "dex", 15, nil,
    {"hero", "human_soldier"}, "dex_magnum_deadeye", "magnum_deadeye", {
        actorText = "Player-controlled actors using a standard player weapon",
        description = "Deadeye enables Aim State for all standard damage-capable player weapons. A completed aim (0.50 seconds of perfect stillness) empowers exactly one next primary attack transaction for x2 damage. If the weapon is the .357 Magnum (which natively supports x2 aim), Deadeye empowers it to x3."
    }, "DEX 15")

Feats.STR_MELEE_REACH = singletonDefinition(
    "STR_MELEE_REACH", "Long Reach", "str", 15, "crowbar",
    {"hero", "human_soldier"}, "str_melee_reach", "melee_reach", {
        meleeReachMultiplier = LONG_REACH_MULTIPLIER,
        actorText = "Player-controlled heroes and human Soldiers with melee-family access",
        description = "Ordinary melee-family reach is multiplied by 1.25, after which the existing geometry trace remains authoritative. This cannot strike through walls, gates, floors, or other blocking architecture."
    }, "STR 15 / melee-family access")

-- Keep the historical CON-prefixed ID for save compatibility; the live GDD now
-- assigns Russian Asset to INT 13.
Feats.CON_RUSSIAN_ASSET = singletonDefinition(
    "CON_RUSSIAN_ASSET", "Russian Asset", "int", 13, "tetris",
    {"hero"}, "int_russian_asset", "russian_asset", {
        tetrisOverfillMultiplier = RUSSIAN_ASSET_REWARD_MULTIPLIER,
        deathTetrisMaxSeconds = RUSSIAN_ASSET_DEATH_TETRIS_SECONDS,
        actorText = "Player-controlled cooperative heroes with Tetris access",
        description = "Doubles all temporary HP overfill earned from qualifying Tetris line-clear rewards, so the baseline single/double/triple/quad rewards become +20/+60/+100/+160 HP, in both death Tetris and post-rescue/victory Tetris. DeathTetrisMaxSeconds increases from 60 to 120 seconds. The mandatory 20-second death/respawn lockout and the 20-second post-rescue/victory window remain unchanged, and F still respawns immediately whenever it is eligible."
    }, "INT 13 / Tetris access")

Catalog.OrdinaryFeats = Feats
Catalog.GateESingletonSourceRevisionId = SOURCE_REVISION

-- Deadeye is offerable only to an actor with actual .357 access, including a
-- later-acquired inventory copy. Preserve every pre-existing capability rule.
if not Progression.LODGateEMagnumCapabilityWrapped then
    Progression.LODGateEMagnumCapabilityWrapped = true
    local baseHasCapability = Progression._HasCapability
    function Progression:_HasCapability(ps, state, tag)
        if tag == "magnum" then
            if ps and ps.starterWeaponClass == "weapon_357" then return true end
            for _, weaponState in ipairs(ps and ps.inventory and ps.inventory.weapons or {}) do
                if weaponState.class == "weapon_357" then return true end
            end
            local run = LOD.RunManager
            if player and isfunction(player.GetAll) and run and run.GetPlayerState then
                for _, actor in ipairs(player.GetAll()) do
                    if IsValid(actor) and run:GetPlayerState(actor) == ps
                        and actor.HasWeapon and actor:HasWeapon("weapon_357")
                    then
                        return true
                    end
                end
            end
            return false
        end
        return baseHasCapability(self, ps, state, tag)
    end
end

local function owns(state, featId)
    for _, ownedId in ipairs(state and state.featIds or {}) do
        if ownedId == featId then return true end
    end
    return false
end

local function stateFor(actorOrState)
    if istable(actorOrState) and actorOrState.featIds then return actorOrState end
    return Rules:ProgressionState(actorOrState)
end

function Effects:SingletonProfile(state)
    local springHeel = owns(state, "DEX_SPRING_HEEL")
    local deadeye = owns(state, "DEX_MAGNUM_DEADEYE")
    local longReach = owns(state, "STR_MELEE_REACH")
    local russianAsset = owns(state, "CON_RUSSIAN_ASSET")
    return {
        springHeel = springHeel,
        jumpHeightMultiplier = springHeel and SPRING_HEEL_HEIGHT_MULTIPLIER or 1,
        jumpImpulseMultiplier = springHeel and SPRING_HEEL_IMPULSE_MULTIPLIER or 1,
        deadeye = deadeye,
        aimHoldSeconds = 0.50,
        magnumAimHoldSeconds = 0.50,
        longReach = longReach,
        meleeReachMultiplier = longReach and LONG_REACH_MULTIPLIER or 1,
        russianAsset = russianAsset,
        tetrisOverfillMultiplier = russianAsset and RUSSIAN_ASSET_REWARD_MULTIPLIER or 1,
        deathTetrisMaxSeconds = russianAsset and RUSSIAN_ASSET_DEATH_TETRIS_SECONDS
            or BASE_DEATH_TETRIS_SECONDS
    }
end

if not Effects.LODGateESingletonApplyDerivedWrapped then
    Effects.LODGateESingletonApplyDerivedWrapped = true
    local base = Effects.ApplyDerived
    function Effects:ApplyDerived(state, derived)
        base(self, state, derived)
        local profile = self:SingletonProfile(state)
        derived.springHeelEnabled = profile.springHeel
        derived.jumpHeightMultiplier = profile.jumpHeightMultiplier
        derived.jumpImpulseMultiplier = profile.jumpImpulseMultiplier
        derived.aimHoldSeconds = profile.aimHoldSeconds
        derived.magnumAimHoldSeconds = profile.magnumAimHoldSeconds
        derived.meleeReachMultiplier = profile.meleeReachMultiplier
        derived.tetrisOverfillMultiplier = profile.tetrisOverfillMultiplier
        derived.deathTetrisMaxSeconds = profile.deathTetrisMaxSeconds
    end
end

function Rules:AimHoldSeconds(actorOrState)
    return Effects:SingletonProfile(stateFor(actorOrState)).aimHoldSeconds
end

function Rules:MagnumAimHoldSeconds(actorOrState)
    return Effects:SingletonProfile(stateFor(actorOrState)).magnumAimHoldSeconds
end

function Rules:SpringHeelImpulseMultiplier(actorOrState)
    return Effects:SingletonProfile(stateFor(actorOrState)).jumpImpulseMultiplier
end

function Rules:SpringHeelHeightMultiplier(actorOrState)
    return Effects:SingletonProfile(stateFor(actorOrState)).jumpHeightMultiplier
end

function Effects:SpringHeelAdditionalImpulse(actorOrState, takeoffImpulse)
    local takeoff = math.max(0, tonumber(takeoffImpulse) or 0)
    return takeoff * math.max(0, Rules:SpringHeelImpulseMultiplier(actorOrState) - 1)
end

function Rules:MeleeReachMultiplier(actorOrState)
    return Effects:SingletonProfile(stateFor(actorOrState)).meleeReachMultiplier
end

function Rules:MeleeReach(actorOrState, baseReach)
    return math.max(0, tonumber(baseReach) or 0) * self:MeleeReachMultiplier(actorOrState)
end

function Rules:TetrisOverfillMultiplier(actorOrState)
    return Effects:SingletonProfile(stateFor(actorOrState)).tetrisOverfillMultiplier
end

function Rules:DeathTetrisMaxSeconds(actorOrState)
    return Effects:SingletonProfile(stateFor(actorOrState)).deathTetrisMaxSeconds
end

function Effects:TetrisOverfillReward(lines, actorOrState)
    local tetris = LOD.Tetris
    local base = tetris and tetris.RewardForLines and tetris.RewardForLines(lines) or 0
    return base * Rules:TetrisOverfillMultiplier(actorOrState)
end

local function addSchemaField(name)
    local fields = RPG.Schema and RPG.Schema.DerivedStats
    if not fields then return end
    for _, existing in ipairs(fields) do
        if existing == name then return end
    end
    fields[#fields + 1] = name
end

for _, field in ipairs({
    "springHeelEnabled", "jumpHeightMultiplier", "jumpImpulseMultiplier",
    "aimHoldSeconds", "magnumAimHoldSeconds", "meleeReachMultiplier"
}) do
    addSchemaField(field)
end

-- Source's ordinary jump impulse has already been applied by the time this
-- zero-delay callback runs. Add only the extra impulse needed for sqrt(2)x
-- takeoff velocity, which produces 2x apex height under unchanged gravity.
hook.Add("KeyPress", "LOD_RPG_GateE_SpringHeel", function(ply, key)
    if key ~= IN_JUMP or not IsValid(ply) or not ply:IsPlayer()
        or not ply:Alive() or not ply:OnGround()
    then
        return
    end

    local stats = Effects.SingletonStats
    stats.jumpAttempts = (stats.jumpAttempts or 0) + 1
    local startZ = ply:GetPos().z
    local multiplier = Rules:SpringHeelImpulseMultiplier(ply)
    stats.lastJumpMultiplier = multiplier

    timer.Simple(0, function()
        if not IsValid(ply) or not ply:Alive() then return end
        local takeoff = ply:GetVelocity().z
        if takeoff <= 0 then return end
        local extra = Effects:SpringHeelAdditionalImpulse(ply, takeoff)
        if extra > 0 then
            ply:SetVelocity(Vector(0, 0, extra))
            stats.jumpBoosts = (stats.jumpBoosts or 0) + 1
        end
        stats.lastJumpImpulse = takeoff
        stats.lastJumpAddedImpulse = extra
        Effects.SpringHeelTraces[ply] = {
            startedAt = CurTime(),
            startZ = startZ,
            apexZ = math.max(startZ, ply:GetPos().z),
            multiplier = multiplier
        }
    end)
end)

hook.Add("Think", "LOD_RPG_GateE_SpringHeelTelemetry", function()
    for ply, trace in pairs(Effects.SpringHeelTraces) do
        if not IsValid(ply) then
            Effects.SpringHeelTraces[ply] = nil
        else
            trace.apexZ = math.max(trace.apexZ or trace.startZ, ply:GetPos().z)
            if CurTime() - trace.startedAt > 0.10 and ply:OnGround() then
                Effects.SingletonStats.lastJumpHeight = math.max(0,
                    (trace.apexZ or trace.startZ) - trace.startZ)
                Effects.SingletonStats.lastJumpMultiplier = trace.multiplier or 1
                if Effects.SingletonStats.expectedEnabled == false then
                    Effects.SingletonStats.baselineJumpHeight =
                        Effects.SingletonStats.lastJumpHeight
                end
                Effects.SpringHeelTraces[ply] = nil
            end
        end
    end
end)

hook.Add("PlayerDeath", "LOD_RPG_GateE_SpringHeelDeath", function(ply)
    Effects.SpringHeelTraces[ply] = nil
end)

function Effects:RecordMeleeReach(reach)
    local stats = self.SingletonStats
    stats.lastMeleeReach = tonumber(reach) or 0
    stats.meleeSwings = (stats.meleeSwings or 0) + 1
end

function Effects:ValidateSingletonFamilies()
    local errors = {}
    local function expect(ok, message)
        if not ok then errors[#errors + 1] = message end
    end
    local expected = {
        DEX_SPRING_HEEL = {"dex", 13, nil, "spring_heel"},
        DEX_MAGNUM_DEADEYE = {"dex", 15, "magnum", "magnum_deadeye"},
        STR_MELEE_REACH = {"str", 15, "crowbar", "melee_reach"},
        CON_RUSSIAN_ASSET = {"int", 13, "tetris", "russian_asset"}
    }
    for id, values in pairs(expected) do
        local feat = Feats[id]
        expect(feat ~= nil, "missing " .. id)
        if feat then
            expect(feat.governingAbilities[1] == values[1], id .. " governing ability")
            expect(feat.abilityRequirements[values[1]] == values[2], id .. " requirement")
            expect((feat.requiredCapabilityTags or {})[1] == values[3], id .. " capability")
            expect(feat.effectHandlerId == values[4], id .. " handler")
        end
    end

    local baseline = self:SingletonProfile({featIds = {}})
    local all = self:SingletonProfile({featIds = {
        "DEX_SPRING_HEEL", "DEX_MAGNUM_DEADEYE", "STR_MELEE_REACH",
        "CON_RUSSIAN_ASSET"
    }})
    expect(baseline.meleeReachMultiplier == 1, "baseline melee reach")
    expect(all.meleeReachMultiplier == 1.25
        and self.SingletonConfig.baseMeleeReach * all.meleeReachMultiplier == 120,
        "Long Reach trace distance")
    expect(baseline.jumpHeightMultiplier == 1 and all.jumpHeightMultiplier == 2,
        "Spring Heel height multiplier")
    expect(math.abs(all.jumpImpulseMultiplier * all.jumpImpulseMultiplier - 2) < 0.00001,
        "Spring Heel impulse produces 2x ballistic height")
    expect(baseline.tetrisOverfillMultiplier == 1
        and baseline.deathTetrisMaxSeconds == 60, "baseline Tetris profile")
    expect(all.tetrisOverfillMultiplier == 2 and all.deathTetrisMaxSeconds == 120,
        "Russian Asset Tetris profile")

    local deadeyeState = {
        featIds = {}, featQualificationAbilities = {dex = 15},
        classId = "rogue", secondaryAbilities = {}, capabilityTags = {}
    }
    local magnumPS = {inventory = {weapons = {{class = "weapon_357"}}}}
    local pistolPS = {inventory = {weapons = {{class = "weapon_pistol"}}}}
    expect(Progression:_FeatEligible(magnumPS, deadeyeState,
        Feats.DEX_MAGNUM_DEADEYE), "Deadeye legal with .357 access")
    expect(not Progression:_FeatEligible(pistolPS, deadeyeState,
        Feats.DEX_MAGNUM_DEADEYE), "Deadeye excludes actor without .357 access")

    local tetris = LOD.Tetris
    if tetris and tetris.RewardForLines then
        local rewards = {10, 30, 50, 80}
        for lines, reward in ipairs(rewards) do
            expect(self:TetrisOverfillReward(lines, {featIds = {}}) == reward,
                "baseline Tetris reward " .. lines)
            expect(self:TetrisOverfillReward(lines,
                {featIds = {"CON_RUSSIAN_ASSET"}}) == reward * 2,
                "Russian Asset Tetris reward " .. lines)
        end
    end

    return #errors == 0, errors
end

if Validation and not Validation.LODGateESingletonsWrapped then
    Validation.LODGateESingletonsWrapped = true
    local base = Validation.Run
    function Validation:Run(printResult)
        local baseOK, errors = base(self, false)
        errors = errors or {}
        local featOK, featErrors = Effects:ValidateSingletonFamilies()
        for _, message in ipairs(featErrors or {}) do
            errors[#errors + 1] = "Gate E singleton families: " .. message
        end
        local ok = baseOK and featOK and #errors == 0
        if printResult ~= false then
            if ok then
                print(string.format(
                    "[LOD:RPG] core RPG validation PASS — gate=%s gameplayEnabled=%s gateESMGHeat=true gateESingletons=true",
                    tostring(RPG.ImplementationGate), tostring(RPG.GameplayEnabled)))
            else
                ErrorNoHalt("[LOD:RPG] core RPG validation FAILED (" .. #errors .. " error(s))\n")
                for _, message in ipairs(errors) do
                    ErrorNoHalt("[LOD:RPG]  - " .. message .. "\n")
                end
            end
        end
        return ok, errors
    end
end

local function developerAllowed(ply)
    local cv = GetConVar("lod_developer_mode")
    return cv and cv:GetBool() and (not IsValid(ply) or ply:IsAdmin())
end

local TEST_IDS = {
    DEX_SPRING_HEEL = true,
    DEX_MAGNUM_DEADEYE = true,
    STR_MELEE_REACH = true,
    CON_RUSSIAN_ASSET = true
}

local function configure(ply, enabled)
    local run = LOD.RunManager
    local ps = run and run.GetPlayerState and run:GetPlayerState(ply) or nil
    local state = ps and ps.progressionState or nil
    if not state then return false, "RPG progression state is unavailable." end
    local kept = {}
    for _, id in ipairs(state.featIds or {}) do
        if not TEST_IDS[id] then kept[#kept + 1] = id end
    end
    state.featIds = kept
    state.featStackCounts = state.featStackCounts or {}
    for id in pairs(TEST_IDS) do state.featStackCounts[id] = nil end
    if enabled then
        for _, id in ipairs({
            "DEX_SPRING_HEEL", "DEX_MAGNUM_DEADEYE", "STR_MELEE_REACH",
            "CON_RUSSIAN_ASSET"
        }) do
            state.featIds[#state.featIds + 1] = id
            state.featStackCounts[id] = 1
        end
    end
    Progression:_RecomputeProgressionState(state)
    Progression:SyncPlayer(ply)
    if run.MarkUnranked then run:MarkUnranked("Gate E singleton feat test") end
    return true
end

local function resetTelemetry(ply, enabled)
    local stats = Effects.SingletonStats
    stats.jumpAttempts = 0
    stats.jumpBoosts = 0
    stats.lastJumpHeight = 0
    stats.lastJumpMultiplier = Rules:SpringHeelImpulseMultiplier(ply)
    stats.lastJumpImpulse = 0
    stats.lastJumpAddedImpulse = 0
    stats.lastMeleeReach = 0
    stats.meleeSwings = 0
    stats.expectedEnabled = enabled == true
    if not enabled then stats.baselineJumpHeight = 0 end
    local magnum = LOD.MagnumSuperExplosive
    if magnum and magnum.Stats then
        magnum.Stats.aimLocks = 0
        magnum.Stats.aimShots = 0
        magnum.Stats.aimCancels = 0
        magnum.Stats.lastAimHoldSeconds = nil
        magnum.Stats.lastAimLockElapsed = nil
    end
end

concommand.Add("lod_rpg_gate_e_singletons_validate", function(ply)
    if not developerAllowed(ply) then return end
    local ok, errors = Effects:ValidateSingletonFamilies()
    if ok then
        print("[LOD:RPG-E] singleton families PASS — Spring Heel 2x height via sqrt(2)x impulse; Long Reach 96->120; Russian Asset rewards x2 and death cap 60s->120s")
    else
        ErrorNoHalt("[LOD:RPG-E] singleton families FAILED\n")
        for _, message in ipairs(errors or {}) do
            ErrorNoHalt("[LOD:RPG-E]  - " .. message .. "\n")
        end
    end
end)

concommand.Add("lod_rpg_gate_e_singletons_status", function(ply)
    if not developerAllowed(ply) or not IsValid(ply) then return end
    local profile = Effects:SingletonProfile(Rules:ProgressionState(ply))
    local stats = Effects.SingletonStats
    local magnum = LOD.MagnumSuperExplosive
    local magnumStats = magnum and magnum.Stats or {}
    local rewards = {}
    for lines = 1, 4 do
        rewards[#rewards + 1] = tostring(Effects:TetrisOverfillReward(lines, ply))
    end
    local expectedReach = BASE_MELEE_REACH * profile.meleeReachMultiplier
    local expectedBoosts = profile.springHeel and 1 or 0
    local acceptance = (stats.jumpAttempts or 0) >= 1
        and (stats.jumpBoosts or 0) >= expectedBoosts
        and (not profile.springHeel or (stats.jumpBoosts or 0) >= 1)
        and (profile.springHeel or (stats.jumpBoosts or 0) == 0)
        and (stats.meleeSwings or 0) >= 1
        and math.abs((stats.lastMeleeReach or 0) - expectedReach) < 0.01
        and (magnumStats.aimLocks or 0) >= 1
    local jumpRatio = (stats.baselineJumpHeight or 0) > 0
        and (stats.lastJumpHeight or 0) / stats.baselineJumpHeight or 0
    local line = string.format(
        "spring=%s impulse=x%.4f jumps=%d boosts=%d lastHeight=%.1f baselineHeight=%.1f ratio=%.2f deadeye=%s hold=%.2fs locks=%d lastLock=%.3fs longReach=%s reach=%.1f lastReach=%.1f swings=%d russian=%s rewards=%s deathCap=%ds acceptance=%s",
        tostring(profile.springHeel), profile.jumpImpulseMultiplier,
        stats.jumpAttempts or 0, stats.jumpBoosts or 0, stats.lastJumpHeight or 0,
        stats.baselineJumpHeight or 0, jumpRatio,
        tostring(profile.deadeye), 0.50,
        magnumStats.aimLocks or 0, magnumStats.lastAimLockElapsed or 0,
        tostring(profile.longReach), expectedReach,
        stats.lastMeleeReach or 0, stats.meleeSwings or 0,
        tostring(profile.russianAsset), table.concat(rewards, "/"),
        profile.deathTetrisMaxSeconds, acceptance and "PASS" or "WAITING")
    print("[LOD:RPG-E] " .. line)
    ply:ChatPrint(line)
end)

concommand.Add("lod_rpg_gate_e_singletons_testkit", function(ply, _, args)
    if not developerAllowed(ply) or not IsValid(ply) or not ply:Alive() then return end
    local enabled = tonumber(args[1]) == 1
    local ok, message = configure(ply, enabled)
    if not ok then ply:ChatPrint(message) return end
    resetTelemetry(ply, enabled)

    local magnum = ply:GetWeapon("weapon_357")
    if not IsValid(magnum) then magnum = ply:Give("weapon_357", true) end
    if IsValid(magnum) then magnum:SetClip1(math.max(1, magnum:Clip1())) end
    local crowbar = ply:GetWeapon("weapon_lod_crowbar")
    if not IsValid(crowbar) then crowbar = ply:Give("weapon_lod_crowbar", true) end
    if IsValid(magnum) then ply:SelectWeapon("weapon_357") end

    local profile = Effects:SingletonProfile(Rules:ProgressionState(ply))
    local line = string.format(
        "Singleton acceptance kit %s: stand perfectly still with Magnum until Aim locks; jump once and land; switch to Crowbar and swing once; then run status. Expected hold=%.2fs, impulse=x%.4f, trace=%.0f, Tetris rewards=%s, death cap=%ds.",
        enabled and "FEATS" or "BASELINE", 0.50,
        profile.jumpImpulseMultiplier, BASE_MELEE_REACH * profile.meleeReachMultiplier,
        enabled and "20/60/100/160" or "10/30/50/80",
        profile.deathTetrisMaxSeconds)
    print("[LOD:RPG-E] " .. line)
    ply:ChatPrint(line)
end)

RPG.SystemBootstrap.FeatEffectSystem = "gate_e_batch_9_singletons"
return Effects
