LOD = LOD or {}
LOD.RPG = LOD.RPG or {}

local RPG = LOD.RPG
local Catalog = RPG.IdentityCatalog
local Feats = Catalog and (Catalog.OrdinaryFeats or Catalog.LevelOneOrdinaryFeats)
local Effects = RPG.FeatEffectSystem
local Rules = LOD.RPGAbilityRules
local Progression = LOD.CharacterProgressionSystem
local Validation = LOD.RPGValidation
if not Feats or not Effects or not Rules or not Progression then return end

local SOURCE_REVISION = "ANLCKQmcBBEnzsnYbFvdzzXmHJB2gAgkhunV5P2pczqttiFNGF1lfRGWUVzYRmO9v_2DdQF2Dpg8w6Ms2v9KI5U5b6HhpuEYa3gnaXvXDA"
local TEST_IDS = {INT_FEEDBACK_LOOP = true, INT_ARC_RECOVERY = true}

local function owns(state, id)
    for _, value in ipairs(state and state.featIds or {}) do
        if value == id then return true end
    end
    return false
end

local function singleton(id, name, requirement, family, handler, description)
    return {
        featId = id,
        displayName = name,
        featFamilyId = family,
        rankIndex = 1,
        replacesLowerRank = false,
        repeatableFallback = false,
        governingAbilities = {"int"},
        abilityRequirements = {int = requirement},
        prerequisiteFeatIds = {},
        requiredCapabilityTags = {"magic_pool"},
        incompatibleFeatIds = {},
        allowedActorTypes = {"hero", "human_soldier", "ai"},
        requiredSubsystemTags = {},
        synergyTags = {family, "magic"},
        oneRank = true,
        effectHandlerId = handler,
        effectParams = {description = description},
        directorBaseWeight = 1.0,
        eligibilityText = string.format("INT %d / magic_pool", requirement),
        actorText = "Heroes, human Soldiers, and Magic-using AI"
    }
end

Feats.INT_FEEDBACK_LOOP = singleton(
    "INT_FEEDBACK_LOOP", "Feedback Loop", 15,
    "int_feedback_loop", "magic_continuation_recovery",
    "Every continuation die actually generated by an offensive Magic attack restores 1 Magic to its caster, capped at 6 restored Magic per committed cast/attack event. Initial dice and unbridged weapon-only Boomchains never count.")

Feats.INT_ARC_RECOVERY = singleton(
    "INT_ARC_RECOVERY", "Arc Recovery", 17,
    "int_arc_recovery", "magic_kill_recovery",
    "Defeating an AI hostile with a Magic-tagged damage event restores 5 Magic, subject to one 2.0-second per-actor internal cooldown and the universal 100-Magic ceiling.")

Catalog.OrdinaryFeats = Feats
Catalog.GateEMagicRecoverySourceRevisionId = SOURCE_REVISION

Effects.MagicRecoveryConfig = {
    sourceRevision = SOURCE_REVISION,
    feedbackPerContinuation = 1,
    feedbackPerCastCap = 6,
    arcRecoveryMagic = 5,
    arcRecoveryCooldownSeconds = 2.0,
    maxMagic = 100
}

Effects.MagicRecoveryStats = Effects.MagicRecoveryStats or {
    continuationDice = 0,
    feedbackLoopRestored = 0,
    magicKills = 0,
    arcRecoveryRestored = 0,
    arcRecoveryCooldownRejects = 0,
    castsWithFeedback = 0
}

function Effects:MagicRecoveryProfile(state)
    return {
        feedbackLoop = owns(state, "INT_FEEDBACK_LOOP"),
        feedbackLoopPerCastCap = owns(state, "INT_FEEDBACK_LOOP") and 6 or 0,
        arcRecovery = owns(state, "INT_ARC_RECOVERY"),
        arcRecoveryMagic = owns(state, "INT_ARC_RECOVERY") and 5 or 0,
        arcRecoveryCooldownSeconds = owns(state, "INT_ARC_RECOVERY") and 2.0 or 0
    }
end

-- Pure ordered transitions. The Force Shout authority owns committed-cast and
-- Magic resource state; these helpers own only the two feat magnitudes/caps.
function Effects:ResolveFeedbackLoop(enabled, continuationDice, alreadyRestored, currentMagic)
    local continuations = math.max(0, math.floor(tonumber(continuationDice) or 0))
    local used = math.Clamp(math.floor(tonumber(alreadyRestored) or 0), 0, 6)
    local magic = math.Clamp(tonumber(currentMagic) or 0, 0, 100)
    if enabled ~= true or continuations <= 0 or used >= 6 or magic >= 100 then
        return magic, 0, used
    end
    local restored = math.min(continuations, 6 - used, 100 - magic)
    return magic + restored, restored, used + restored
end

function Effects:ResolveArcRecovery(enabled, defeatedAI, now, readyAt, currentMagic)
    local magic = math.Clamp(tonumber(currentMagic) or 0, 0, 100)
    local at = tonumber(now) or 0
    local ready = tonumber(readyAt) or 0
    if enabled ~= true or defeatedAI ~= true or at < ready or magic >= 100 then
        return magic, 0, ready, false
    end
    local restored = math.min(5, 100 - magic)
    return magic + restored, restored, at + 2.0, true
end

function Effects:ApplyFeedbackLoop(actor, resourceState, continuationDice, alreadyRestored)
    local profile = self:MagicRecoveryProfile(Rules:ProgressionState(actor))
    local current = tonumber(resourceState and resourceState.magic) or 0
    local magic, restored, used = self:ResolveFeedbackLoop(
        profile.feedbackLoop, continuationDice, alreadyRestored, current)
    if resourceState then resourceState.magic = magic end
    local stats = self.MagicRecoveryStats
    stats.continuationDice = (stats.continuationDice or 0)
        + math.max(0, math.floor(tonumber(continuationDice) or 0))
    stats.feedbackLoopRestored = (stats.feedbackLoopRestored or 0) + restored
    return restored, used
end

function Effects:ApplyArcRecovery(actor, resourceState, defeatedAI, now)
    local profile = self:MagicRecoveryProfile(Rules:ProgressionState(actor))
    local current = tonumber(resourceState and resourceState.magic) or 0
    local readyAt = tonumber(resourceState and resourceState.arcRecoveryReadyAt) or 0
    local magic, restored, nextReady, triggered = self:ResolveArcRecovery(
        profile.arcRecovery, defeatedAI, now, readyAt, current)
    if resourceState then
        resourceState.magic = magic
        resourceState.arcRecoveryReadyAt = nextReady
    end
    local stats = self.MagicRecoveryStats
    if defeatedAI then stats.magicKills = (stats.magicKills or 0) + 1 end
    if triggered then
        stats.arcRecoveryRestored = (stats.arcRecoveryRestored or 0) + restored
    elseif defeatedAI and profile.arcRecovery and (tonumber(now) or 0) < readyAt then
        stats.arcRecoveryCooldownRejects = (stats.arcRecoveryCooldownRejects or 0) + 1
    end
    return restored, triggered
end

if not Effects.LODGateEMagicRecoveryApplyDerivedWrapped then
    Effects.LODGateEMagicRecoveryApplyDerivedWrapped = true
    local base = Effects.ApplyDerived
    function Effects:ApplyDerived(state, derived)
        base(self, state, derived)
        local profile = self:MagicRecoveryProfile(state)
        derived.feedbackLoopEnabled = profile.feedbackLoop
        derived.feedbackLoopPerCastCap = profile.feedbackLoopPerCastCap
        derived.arcRecoveryEnabled = profile.arcRecovery
        derived.arcRecoveryMagic = profile.arcRecoveryMagic
        derived.arcRecoveryCooldownSeconds = profile.arcRecoveryCooldownSeconds
    end
end

local function addSchemaField(name)
    local fields = RPG.Schema and RPG.Schema.DerivedStats
    if not fields then return end
    for _, existing in ipairs(fields) do
        if existing == name then return end
    end
    fields[#fields + 1] = name
end

for _, field in ipairs({
    "feedbackLoopEnabled", "feedbackLoopPerCastCap", "arcRecoveryEnabled",
    "arcRecoveryMagic", "arcRecoveryCooldownSeconds"
}) do
    addSchemaField(field)
end

if not Progression.LODGateEMagicRecoverySnapshotWrapped then
    Progression.LODGateEMagicRecoverySnapshotWrapped = true
    local base = Progression.BuildClientSnapshot
    function Progression:BuildClientSnapshot(ply)
        local snapshot = base(self, ply)
        if not snapshot then return nil end
        local derived = Rules:Derived(ply) or {}
        snapshot.feedbackLoopEnabled = derived.feedbackLoopEnabled == true
        snapshot.feedbackLoopPerCastCap = derived.feedbackLoopPerCastCap or 0
        snapshot.arcRecoveryEnabled = derived.arcRecoveryEnabled == true
        snapshot.arcRecoveryMagic = derived.arcRecoveryMagic or 0
        snapshot.arcRecoveryCooldownSeconds = derived.arcRecoveryCooldownSeconds or 0
        return snapshot
    end
end

function Effects:ValidateMagicRecoveryFamilies()
    local errors = {}
    local function expect(ok, message)
        if not ok then errors[#errors + 1] = message end
    end
    local feedback = Feats.INT_FEEDBACK_LOOP
    local arc = Feats.INT_ARC_RECOVERY
    expect(feedback and feedback.abilityRequirements.int == 15, "Feedback Loop INT 15")
    expect(arc and arc.abilityRequirements.int == 17, "Arc Recovery INT 17")
    expect(feedback and feedback.effectHandlerId == "magic_continuation_recovery",
        "Feedback Loop handler")
    expect(arc and arc.effectHandlerId == "magic_kill_recovery", "Arc Recovery handler")

    local baseline = self:MagicRecoveryProfile({featIds = {}})
    local both = self:MagicRecoveryProfile({featIds = {
        "INT_FEEDBACK_LOOP", "INT_ARC_RECOVERY"
    }})
    expect(not baseline.feedbackLoop and not baseline.arcRecovery,
        "baseline recovery disabled")
    expect(both.feedbackLoop and both.feedbackLoopPerCastCap == 6,
        "Feedback Loop profile")
    expect(both.arcRecovery and both.arcRecoveryMagic == 5
        and both.arcRecoveryCooldownSeconds == 2.0, "Arc Recovery profile")

    local magic, restored, used = self:ResolveFeedbackLoop(true, 8, 0, 70)
    expect(magic == 76 and restored == 6 and used == 6,
        "Feedback Loop six-Magic committed-cast cap")
    magic, restored, used = self:ResolveFeedbackLoop(true, 2, 5, 99)
    expect(magic == 100 and restored == 1 and used == 6,
        "Feedback Loop universal Magic ceiling")
    magic, restored = self:ResolveFeedbackLoop(false, 8, 0, 70)
    expect(magic == 70 and restored == 0, "baseline continuation isolation")

    local nextReady, triggered
    magic, restored, nextReady, triggered = self:ResolveArcRecovery(true, true, 10, 0, 70)
    expect(magic == 75 and restored == 5 and nextReady == 12 and triggered,
        "Arc Recovery kill restore and cooldown")
    magic, restored, nextReady, triggered = self:ResolveArcRecovery(true, true, 11, nextReady, magic)
    expect(magic == 75 and restored == 0 and nextReady == 12 and not triggered,
        "Arc Recovery cooldown rejects clustered kill")
    magic, restored, nextReady, triggered = self:ResolveArcRecovery(true, true, 12, nextReady, 98)
    expect(magic == 100 and restored == 2 and nextReady == 14 and triggered,
        "Arc Recovery caps at 100 Magic")
    return #errors == 0, errors
end

if Validation and not Validation.LODGateEMagicRecoveryWrapped then
    Validation.LODGateEMagicRecoveryWrapped = true
    local base = Validation.Run
    function Validation:Run(printResult)
        local baseOK, errors = base(self, false)
        errors = errors or {}
        local featOK, featErrors = Effects:ValidateMagicRecoveryFamilies()
        for _, message in ipairs(featErrors or {}) do
            errors[#errors + 1] = "Gate E Magic recovery: " .. message
        end
        local ok = baseOK and featOK and #errors == 0
        if printResult ~= false then
            if ok then
                print(string.format(
                    "[LOD:RPG] core RPG validation PASS — gate=%s gameplayEnabled=%s gateEMagicRecovery=true",
                    tostring(RPG.ImplementationGate), tostring(RPG.GameplayEnabled)))
            else
                ErrorNoHalt("[LOD:RPG] core RPG validation FAILED (" .. #errors .. " error(s))\n")
                for _, message in ipairs(errors) do
                    ErrorNoHalt("[LOD:RPG]  - " .. message .. "\n")
                end
            end
        end
        return ok, errors
    end
end

local function developerAllowed(ply)
    local cv = GetConVar("lod_developer_mode")
    return cv and cv:GetBool() and (not IsValid(ply) or ply:IsAdmin())
end

local function configurePlayer(ply, enabled)
    local run = LOD.RunManager
    local ps = run and run.GetPlayerState and run:GetPlayerState(ply) or nil
    local state = ps and ps.progressionState or nil
    if not state then return nil, "RPG progression state is unavailable." end
    local kept = {}
    for _, id in ipairs(state.featIds or {}) do
        if not TEST_IDS[id] then kept[#kept + 1] = id end
    end
    state.featIds = kept
    state.featStackCounts = state.featStackCounts or {}
    for id in pairs(TEST_IDS) do state.featStackCounts[id] = nil end
    if enabled then
        for _, id in ipairs({"INT_FEEDBACK_LOOP", "INT_ARC_RECOVERY"}) do
            state.featIds[#state.featIds + 1] = id
            state.featStackCounts[id] = 1
        end
    end
    Progression:_RecomputeProgressionState(state)
    Progression:SyncPlayer(ply)
    ps.magic = 30
    ps.arcRecoveryReadyAt = 0
    local magic = LOD.Magic
    if magic and magic.NextCast then magic.NextCast[ply] = 0 end
    if magic and magic._Sync then magic:_Sync(ply, ps) end
    if run.MarkUnranked then run:MarkUnranked("Gate E Magic recovery feat test") end
    return ps
end

local function resetTelemetry(enabled)
    local stats = Effects.MagicRecoveryStats
    stats.continuationDice = 0
    stats.feedbackLoopRestored = 0
    stats.magicKills = 0
    stats.arcRecoveryRestored = 0
    stats.arcRecoveryCooldownRejects = 0
    stats.castsWithFeedback = 0
    stats.expectedEnabled = enabled == true
end

concommand.Add("lod_rpg_gate_e_magic_recovery_validate", function(ply)
    if not developerAllowed(ply) then return end
    local ok, errors = Effects:ValidateMagicRecoveryFamilies()
    if ok then
        print("[LOD:RPG-E] Magic recovery PASS — Feedback Loop +1 per continuation/cap 6; Arc Recovery +5/cooldown 2.0s")
    else
        ErrorNoHalt("[LOD:RPG-E] Magic recovery FAILED\n")
        for _, message in ipairs(errors or {}) do
            ErrorNoHalt("[LOD:RPG-E]  - " .. message .. "\n")
        end
    end
end)

concommand.Add("lod_rpg_gate_e_magic_recovery_status", function(ply)
    if not developerAllowed(ply) or not IsValid(ply) then return end
    local run = LOD.RunManager
    local ps = run and run.GetPlayerState and run:GetPlayerState(ply) or nil
    local profile = Effects:MagicRecoveryProfile(Rules:ProgressionState(ply))
    local stats = Effects.MagicRecoveryStats
    local arcRemaining = math.max(0, (tonumber(ps and ps.arcRecoveryReadyAt) or 0) - CurTime())
    local baselineOK = not profile.feedbackLoop and not profile.arcRecovery
        and (stats.feedbackLoopRestored or 0) == 0 and (stats.arcRecoveryRestored or 0) == 0
    local featOK = profile.feedbackLoop and profile.arcRecovery
        and (stats.feedbackLoopRestored or 0) >= 1
        and (stats.magicKills or 0) >= 1 and (stats.arcRecoveryRestored or 0) >= 1
    local line = string.format(
        "feedback=%s continuations=%d restored=%d cap=6 arc=%s kills=%d restored=%d cooldownRejects=%d readyIn=%.2fs magic=%.2f acceptance=%s",
        tostring(profile.feedbackLoop), stats.continuationDice or 0,
        stats.feedbackLoopRestored or 0, tostring(profile.arcRecovery),
        stats.magicKills or 0, stats.arcRecoveryRestored or 0,
        stats.arcRecoveryCooldownRejects or 0, arcRemaining,
        tonumber(ps and ps.magic) or 0, (baselineOK or featOK) and "PASS" or "WAITING")
    print("[LOD:RPG-E] " .. line)
    ply:ChatPrint(line)
end)

concommand.Add("lod_rpg_gate_e_magic_recovery_testkit", function(ply, _, args)
    if not developerAllowed(ply) or not IsValid(ply) or not ply:Alive() then return end
    local enabled = tonumber(args[1]) == 1
    local ps, message = configurePlayer(ply, enabled)
    if not ps then ply:ChatPrint(message) return end
    resetTelemetry(enabled)
    local prepared = 0
    for _, hostile in ipairs(LOD.HostileRegistry and LOD.HostileRegistry:List() or {}) do
        if IsValid(hostile) and hostile.LODHostile and not hostile.LODDead and hostile:Health() > 0 then
            hostile:SetHealth(1)
            prepared = prepared + 1
        end
    end
    local line = string.format(
        "Batch 12 %s: Magic=30; %d one-HP targets. Aim, RMB, wait 1s, then run magic_recovery_status; rerun if no continuation rolled.",
        enabled and "FEATS" or "BASELINE", prepared)
    print("[LOD:RPG-E] " .. line)
    ply:ChatPrint(line)
end)

RPG.SystemBootstrap.FeatEffectSystem = "gate_e_batch_12_magic_recovery"
return Effects
