-- Generated by tools/build_manual.py; edit docs/manual/book.json.
return [====[();return;}if(tag==='INPUT'||tag==='SELECT'||tag==='TEXTAREA')return;if(e.keyCode===37){show(current-1);e.preventDefault();}else if(e.keyCode===39){show(current+1);e.preventDefault();}else {call('tab',e.keyCode,e.key||'');if(e.keyCode===80||e.keyCode===73||e.keyCode===76||e.keyCode===79)e.preventDefault();}};
window.LODManual={restore:function(n,top,size){scale(parseInt(size,10)||18);show(n,Math.max(0,Number(top)||0));},go:show};
show(0,0);call('ready');
})();</script></body></html>]====]
